'use strict'

/*
|--------------------------------------------------------------------------
| AlbumSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use('Factory')
const Album = use('App/Models/Album')

class AlbumSeeder {
  async run () {
    await Album.createMany([

      {
        name: 'Espelho da Alma',
        release_date: 2011,
        cover: 'https://f4.bcbits.com/img/a3899010157_16.jpg',
        about: 'No registry',
        copies_sold: null,
        studio_id:3,
      },
      {
        name: 'Além Daquilo Que Te Cega',
        release_date: 2014,
        cover: 'https://f4.bcbits.com/img/a0737351744_10.jpg',
        about: 'No Registry',
        copies_sold: null,
        studio_id:4,
      },
      {
        name: 'Viva Como Se Houvesse Um Final (Ao Vivo)',
        release_date: 2016,
        cover: 'https://f4.bcbits.com/img/a3520339471_16.jpg',
        about: 'No Registry',
        copies_sold: null,
        studio_id:1,
      },
      {
        name: 'Realidade, Vida e Fé',
        release_date: 2018,
        cover: 'https://f4.bcbits.com/img/a0465067803_16.jpg',
        about: 'No Registry',
        copies_sold: null,
        studio_id:1,
      },
      {
        name: 'Lados_opostos',
        release_date: 2005,
        cover: 'https://f4.bcbits.com/img/a4123900748_16.jpg',
        about: 'Gravado, mixado e masterizado no começo de 2004 no AML Estúdio, em Florianópolis/SC, por Andrei e Alexei Leão.\\n Todas as letras e músicas por Display.\\n Formação da época era Tiago Garcia (vocal), Juliano Jover (guitarra), Elvis Volpatto (bateria) e Márcio Rocha (baixo).',
        copies_sold: null,
        studio_id:2,
      },
      {
        name: 'Um Dia Pra Sonhar',
        release_date: 2007,
        cover: 'https://f4.bcbits.com/img/a0456336171_16.jpg',
        about: 'CD/DVD Um Dia Pra Sonhar.\\nGravado, mixado e masterizado no começo de 2006 no AML Estúdio, em Florianópolis/SC, por Andrei e Alexei Leão.\\nTodas as letras e músicas por Display.\\nFormação da época era Tiago Garcia (vocal), Juliano Jover (guitarra), Elvis Volpatto (bateria) e Márcio Rocha (baixo).',
        copies_sold: null,
        studio_id:6,
      },
      {
        name: 'A Marcha do Mundo, Vol. 1',
        release_date: 2015,
        cover: 'https://f4.bcbits.com/img/a3885155840_16.jpg',
        about: 'A Marcha Do Mundo, Vol. 1.\nnBaterias e guitarras gravadas no AML Estúdio, Florianópolis/SC, entre abril e maio de 2009. Vocais e baixos gravados por Juliano Jover no Half Beach Sounds, Itapema/SC, entre fevereiro e março de 2015. Mix e master por Francisco Maffei, Caxias do Sul/RS, em abril de 2015.\\nTodas as letras e músicas por Display.',
        copies_sold: null,
        studio_id:6,
      },
      {
        name: 'A Marcha do Mundo, Vol. 2',
        release_date: 2017,
        cover: 'https://f4.bcbits.com/img/a2394729427_16.jpg',
        about: 'A Marcha Do Mundo, Vol. 2.\\n Baterias e guitarras gravadas no Estúdio Raphael Campos, Florianópolis/SC, entre abril e maio de 2016. Vocais e baixos gravados por Juliano Jover entre janeiro e março de 2017. Mix e master por André Bresiani, Tubarão/SC, em abril de 2017.',
        copies_sold: null,
        studio_id:6,
      },
      {
        name: 'Pintando Quadros do Invisível',
        release_date: 2016,
        cover: 'https://lastfm.freetls.fastly.net/i/u/770x0/f30d9b6a4bf84046769dcd37278c2a0f.webp#f30d9b6a4bf84046769dcd37278c2a0f',
        about: 'No Registry',
        copies_sold: '0',
        studio_id:2,
      },
      {
        name: 'Norte',
        release_date: 2018,
        cover: 'https://lastfm.freetls.fastly.net/i/u/770x0/0b11294762f4983c229027775b9f8dbf.webp',
        about: 'No History',
        copies_sold: '0',
        studio_id:2,
      },
      {
        name: 'Ciclo Interminável',
        release_date: 2008,
        cover: 'https://www.spirit-of-metal.com/les%20goupes/P/Ponto%20Nulo%20No%20Ceu/Ciclo%20Interminavel/Ciclo%20Interminavel.jpg',
        about: 'No Registry',
        copies_sold: null,
        studio_id:2,
      },
      {
        name: 'Brilho Cego',
        release_date: 2011,
        cover: 'https://www.spirit-of-metal.com/les%20goupes/P/Ponto%20Nulo%20No%20Ceu/Brilho%20Cego/Brilho%20Cego.jpg',
        about: 'No Registry',
        copies_sold: null,
        studio_id:2,
      },
      {
        name: 'Transpiração Contínua Prolongada',
        release_date: 1997,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/e/eb/Transpiração_contínua_prolongada.jpg/220px-Transpiração_contínua_prolongada.jpg',
        about: 'Transpiração Contínua Prolongada é o primeiro álbum da banda brasileira de rock Charlie Brown Jr. Ele foi lançado em 16 de Junho de 1997 com o selo Virgin Records, que na época tinha como presidente o produtor musical Rick Bonadio. O nome do álbum é uma menção ao esforço que a banda fez para poder gravar o álbum e do tanto de suor que eles derramaram até o seu lançamento. A faixa "Charlie Brown Jr. (Deixa Estar Que Eu Sigo Em Frente)" define bem esta batalha que a banda teve que enfrentar até chegar conseguirem gravar este álbum.',
        copies_sold: '250000',
        studio_id:7,
      },
      {
        name: 'Preço Curto... Prazo Longo',
        release_date: 1999,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/2/22/PCPL1999.jpg/220px-PCPL1999.jpg',
        about: 'Preço Curto... Prazo Longo é o segundo álbum da banda de rock brasileira Charlie Brown Jr. Ele foi lançado no dia 6 de março de 1999 pela gravadora Virgin Records. Sobre o nome do álbum, o vocalista Chorão deu a seguinte explicação: \\nNós fazíamos os shows, mas acabava muito rápido, porque tinham poucas músicas. Então resolvemos gravar muitas músicas para tocarmos mais tempo nos shows. Mas não queríamos que fosse um CD caro. Então é como se fosse um CD duplo, mas com preço de CD simples. \\nChorão, sobre o nome do álbum\\nApresentando um repertório mais alternativo e compacto, criando uma junção entre vários gêneros musicais como o hardcore, o rap, o reggae e o surf music, consagrando assim uma nova fase e identidade á banda, no álbum estão os hits "Zóio de Lula" (a primeira música da banda a alcançar a primeira posição nas rádios brasileiras), "Te Levar" (famosa por ter sido o segundo tema da soap opera Malhação, substituindo "Assim Caminha a Humanidade", de Lulu Santos), "Não Deixe o Mar te Engolir" e "Confisco", que tem uma letra autobiográfica onde o protagonista tem todos os seus bens confiscados..No Brasil vendeu mais de 250 mil cópias, sendo certificado com Disco de Platina pela ABPD. Segundo o site G1, até 2013, 464.560 unidades do disco haviam sido comercializadas. \\nEm 2013, aproveitando a comoção causada pela morte do Chorão, a gravadora EMI relançou este álbum, em seu formato original.',
        copies_sold: '464560',
        studio_id:7,
      },
      {
        name: 'Nadando com os Tubarões',
        release_date: 2000,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/0/04/Nadando_com_os_Tubar%C3%B5es.jpg/220px-Nadando_com_os_Tubar%C3%B5es.jpg',
        about: 'Nadando com os Tubarões é o terceiro álbum de estúdio da banda brasileira de skate punk Charlie Brown Jr. Foi lançado em 2000 pelo selo Virgin Records. Foi o último álbum com a formação original do Charlie Brown Jr. (conhecida como formação clássica), já que Thiago Castanho, alegando problemas de agenda, saiu da banda após a turnê deste álbum. \\nNadando com os Tubarões traz o sucesso "Não é Sério". Seu lançamento foi fundamental para firmar a banda santista como um dos maiores nomes no cenário do rock brasileiro.',
        copies_sold: '100000',
        studio_id:7,
      },
      {
        name: '100% Charlie Brown Jr. - Abalando a sua Fábrica',
        release_date: 2001,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/0/00/100%25_Charlie_Brown_Jr._-_Abalando_a_sua_F%C3%A1brica.jpg/220px-100%25_Charlie_Brown_Jr._-_Abalando_a_sua_F%C3%A1brica.jpg',
        about: '100% Charlie Brown Jr. - Abalando A Sua Fábrica é o quarto álbum de estúdio da banda de rock brasileira Charlie Brown Jr. Ele foi lançado em novembro de 2001 com o selo EMI, sendo o primeiro álbum da banda fora do selo Virgin, que apesar de ser da EMI, eram operações diferentes',
        copies_sold: '100000',
        studio_id:7,
      },
      {
        name: 'Bocas Ordinárias',
        release_date: 2002,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/5/5d/Bocas_Ordin%C3%A1rias.jpg/220px-Bocas_Ordin%C3%A1rias.jpg',
        about: 'Bocas Ordinárias é o quinto álbum de estúdio - e o sexto de sua discografia - da banda de rock brasileira Charlie Brown Jr.. O álbum foi lançado em 2002 e, segundo Chorão, o vocalista da banda, o álbum seria uma continuação do álbum anterior (100% Charlie Brown Jr. (Abalando a sua Fábrica)), no sentido de ter mais Rock do que os outros álbuns. O álbum vendeu 500 mil cópias, rendendo um disco de ouro à banda.',
        copies_sold: '500000',
        studio_id:7,
      },
      {
        name: 'Tâmo Aí na Atividade',
        release_date: 2004,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/b/bf/Tamo_A%C3%AD_na_Atividade.jpg/220px-Tamo_A%C3%AD_na_Atividade.jpg',
        about: 'Tamo Aí na Atividade é o sexto álbum de estúdio - e o sétimo da discografia - da banda de rock brasileira Charlie Brown Jr. Ele foi lançado em 2004, com o selo EMI.',
        copies_sold: '100000',
        studio_id:7,
      },
      {
        name: 'Imunidade Musical',
        release_date: 2005,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/4/48/Imunidade_Musical.jpg/220px-Imunidade_Musical.jpg',
        about: 'Imunidade Musical é o sétimo álbum de estúdio da banda Charlie Brown Jr. Ele foi lançado em 23 de agosto de 2005. Oitavo álbum do grupo, tem mais de 20 faixas (a maioria de autoria do vocalista Chorão), e inaugura uma nova formação: André Ruas, conhecido como Pinguim, na bateria e beat-box; Heitor Gomes, filho do baixista brasileiro Chico Gomes, no baixo elétrico; e Thiago Castanho, guitarrista da primeira formação (1997 a 2000), que retorna à banda. No Brasil vendeu mais de 100 mil cópias, sendo certificado com Disco de Ouro pela ABPD. Foi o primeiro sem o baixista Champignon, o guitarrista Marcão (ambos iriam retornar em 2011) e o baterista Renato Pelado.',
        copies_sold: '100000',
        studio_id:7,
      },
      {
        name: 'Ritmo, Ritual e Responsa',
        release_date: 2007,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/9/99/Ritmo%2C_Ritual_e_Responsa.jpg/220px-Ritmo%2C_Ritual_e_Responsa.jpg',
        about: 'Ritmo, Ritual e Responsa é o nono álbum da banda santista Charlie Brown Jr.. Com produção de Chorão e Thiago Castanho, o trabalho dos santistas é um dos mais requisitados por fãs do Brasil. As 23 faixas do CD compõem a primeira parte da trilha sonora do filme O Magnata, que é o primeiro longa-metragem roteirizado por Chorão, o vocalista e líder do grupo. O álbum traz as participações especiais de amigos da banda como MV Bill, Ratos de Porão, o produtor português de Electro Rock, Paranormal Attack, Lobotomia e Forfun.',
        copies_sold: null,
        studio_id:7,
      },
      {
        name: 'Camisa 10 (Joga Bola até na Chuva)',
        release_date: 2009,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/0/02/Camisa10_-Joga_Bola_At%C3%A9_na_Chuva.jpg/220px-Camisa10_-Joga_Bola_At%C3%A9_na_Chuva.jpg',
        about: 'Camisa 10 Joga Bola até na Chuva é o décimo álbum de estúdio da banda brasileira de rock Charlie Brown Jr. Lançado em 2009 e produzido por Rick Bonadio, é o primeiro disco da banda com o selo Sony Music e o primeiro de inéditas desde o trabalho Ritmo, Ritual e Responsa, de 2007.',
        copies_sold: '100000',
        studio_id:7,
      },
      {
        name: 'La Família 013',
        release_date: 2013,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/7/76/La_Fam%C3%ADlia_013.jpg/220px-La_Fam%C3%ADlia_013.jpg',
        about: 'La Família 013 é o décimo primeiro e último álbum de estúdio da banda de rock brasileira Charlie Brown Jr., e o primeiro álbum da banda lançado após a morte do Chorão. Lançado no dia 8 de outubro de 2013 pela Som Livre. O lançamento seria em setembro, porém a morte do co-fundador da banda Charlie Brown Jr., Champignon, atrasou este prazo. No dia 24 de setembro de 2013 ocorreu o vazamento do álbum antes do seu lançamento oficial e foi disponibilizado na página do Deezer.',
        copies_sold: '40000',
        studio_id:7,
      },
      {
        name: 'Acústico MTV - Charlie Brown Jr.',
        release_date: 2003,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/1/17/Ac%C3%BAstico_MTV_-_Charlie_Brown_Jr..jpg/240px-Ac%C3%BAstico_MTV_-_Charlie_Brown_Jr..jpg',
        about: 'Acústico MTV - Charlie Brown Jr. é o álbum musical da série Acústico MTV da banda brasileira Charlie Brown Jr. transmitido pela MTV Brasil e lançado em 2003 pela gravadora EMI em CD e DVD. Trata-se do primeiro álbum ao vivo da banda, o sexto de sua discografia, e o segundo DVD. \\nNo Brasil, o álbum vendeu mais de 250 mil cópias, sendo certificado com Disco de Platina pela ABPD. Foi o 3º DVD mais vendido de 2003, e o 9º CD mais vendido do ano. Em 2020, a revista Rolling Stone Brasil o elegeu como um dos 11 melhores Acústicos MTV brasileiros de todos os tempos.',
        copies_sold: '600000',
        studio_id:7,
      },
      {
        name: 'Música Popular Caiçara (Ao Vivo)',
        release_date: 2012,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/e/ec/M%C3%BAsica_Popular_Cai%C3%A7ara.jpg/220px-M%C3%BAsica_Popular_Cai%C3%A7ara.jpg',
        about: 'Música Popular Caiçara - Ao Vivo, ou simplesmente Música Popular Caiçara é um álbum ao vivo da banda de rock Charlie Brown Jr., lançado em Maio de 2012 pelo selo independente Radar Records, em CD produzido por Liminha, DVD e Blu-ray dirigido por KondZilla. É o último álbum lançado com o vocalista Chorão em vida. A versão em CD é bastante reduzida em relação ao DVD e Blu-ray, pois enquanto as versões em vídeo trazem 28 músicas, o CD traz apenas 15. Por conta disso, em 2016, a Radar Records lançou o CD Música Popular Caiçara - Ao Vivo - Vol.2, contendo o áudio das faixas que estavam presentes no DVD e Blu-ray, mas não no formato em CD, mais uma versão ao vivo de Céu Azul.',
        copies_sold: '100000',
        studio_id:7,
      },
      {
        name: 'Música Popular Caiçara (Ao Vivo) Vol.2',
        release_date: 2016,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/c/cf/Musica_Popular_Cai%C3%A7ara_2.jpg/220px-Musica_Popular_Cai%C3%A7ara_2.jpg',
        about: 'Música Popular Caiçara - Ao Vivo, ou simplesmente Música Popular Caiçara é um álbum ao vivo da banda de rock Charlie Brown Jr., lançado em Maio de 2012 pelo selo independente Radar Records, em CD produzido por Liminha, DVD e Blu-ray dirigido por KondZilla. É o último álbum lançado com o vocalista Chorão em vida. A versão em CD é bastante reduzida em relação ao DVD e Blu-ray, pois enquanto as versões em vídeo trazem 28 músicas, o CD traz apenas 15. Por conta disso, em 2016, a Radar Records lançou o CD Música Popular Caiçara - Ao Vivo - Vol.2, contendo o áudio das faixas que estavam presentes no DVD e Blu-ray, mas não no formato em CD, mais uma versão ao vivo de Céu Azul.',
        copies_sold: '100000',
        studio_id:7,
      },
      {
        name: 'Yoga, Stress e Cafeína',
        release_date: 2006,
        cover: 'https://studiosol-a.akamaihd.net/letras/272x272/albuns/d/a/3/7/22177.jpg',
        about: 'No Registry',
        copies_sold: null,
        studio_id:8,
      },
      {
        name: 'Liberta',
        release_date: 2008,
        cover: 'https://www.tenhomaisdiscosqueamigos.com/wp-content/uploads/2018/09/rancore-liberta-capa.jpg',
        about: 'Após o disco de estreia em 2006 (“Yoga, Stress e Cafeina”), que mostrou a todos que o verdadeiro hardcore nacional estava mais vivo do que nunca, a banda paulistana Rancore lançou em 2008 seu segundo álbum ”Liberta”. Esse trabalho apresentou um Rancore mais maduro e aberto a novas experiências musicais, afastando-se do paradigma de ser apenas mais uma novidade da cena nacional para se tornar uma das melhores bandas da cena underground nacional. Devido à boa repercussão desse trabalho a Deck lança em 2015 “Liberta” em formato digital.',
        copies_sold: null,
        studio_id:8,
      },
      {
        name: 'Seiva',
        release_date: 2011,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/3/36/Seiva_%28álbum%29.jpg/220px-Seiva_%28álbum%29.jpg',
        about: 'Seiva é o terceiro álbum de estúdio da banda brasileira de rock Rancore. O álbum é o primeiro disco da banda pela gravadora Deckdisc e foi produzido por Rafael Ramos, mesmo produtor de bandas famosas como Cachorro Grande e Pitty. O disco foi gravado em 2010, no Rio de Janeiro. \\nO álbum tem seu direcionamento musical mais voltado para experimentações e sons alternativos, diferentemente dos primeiros discos, em que seus sons eram voltados a gêneros como punk rock e hardcore punk. \\nFoi extremamente bem-sucedido, gerando uma turnê de 3 anos pelo país, 7 singles com videoclipes, sendo que o single Mãe foi trilha sonora da série Malhação, da Rede Globo, além de ótimas críticas, sendo considerado por grandes veículos musicais, como o site Tenho Mais Disco Que Amigos! como o melhor disco brasileiro do ano.',
        copies_sold: null,
        studio_id:8,
      },
      {
        name: 'Acervo Rancore Ao Vivo',
        release_date: 2014,
        cover: 'https://i.musiocdn.com/s2Znro1Vn3FcrihX80kHvmnScVs=/300x300/smart/artist/4415/album/11211/rancore-acervo-rancore-ao-vivo.jpg',
        about: 'No Registry',
        copies_sold: null,
        studio_id:8,
      },
      {
        name: 'Raimundos',
        release_date: 1994,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/6/60/Raimundos1994.jpg/220px-Raimundos1994.jpg',
        about: 'Raimundos é o álbum de estreia da banda de rock brasileira Raimundos, lançado em 1994 pelo selo Banguela Records, criado pela banda paulista Titãs em parceria com Carlos Eduardo Miranda, que assina a produção do álbum, gravado no estúdio Be Bop, em São Paulo. Foi com a canção "Nêga Jurema" que surgiu o primeiro vídeo musical da banda, direcionado por José Eduardo Belmonte. Apesar do clipe ser de produção precária, devido a pedidos do próprio público, ele participou da escolha da audiência na MTV, para representar o Brasil nos Estados Unidos, concorrendo com o videoclipe "Territory", da banda mineira de thrash metal Sepultura (que saiu vencedora).',
        copies_sold: '100000',
        studio_id:9,
      },
      {
        name: 'Lavô Tá Novo',
        release_date: 1995,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/1/18/LavoTaNovo.jpg/220px-LavoTaNovo.jpg',
        about: 'Lavô Tá Novo é o segundo álbum de estúdio da banda de rock brasileira Raimundos, foi lançado em 3 de Novembro de 1995 pela gravadora Warner Music e foi produzido pelo norte-americano Mark Dearnley, que já trabalhou com AC/DC, Black Sabbath e Def Leppard. Na época, o disco vendeu em torno de 400 mil cópias.',
        copies_sold: '400000',
        studio_id:9,
      },
      {
        name: 'Cesta Básica',
        release_date: 1996,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/0/08/Cesta_basica_1996.jpg/220px-Cesta_basica_1996.jpg',
        about: 'Cesta Básica é uma coletânea em formato box lançada pela banda de rock brasileira Raimundos, em 21 de novembro de 1996. É formada por uma revista em quadrinhos chamada Puteiro em João Pessoa, criada pelo cartunista Angeli; um vídeo em VHS de 48 minutos, com trechos de apresentações e clipes da banda, um adesivo; e um CD formado por 10 faixas. \\nO CD inclui três canções inéditas: Papeau Nuky Doe, A sua e Infeliz Natal; dois covers (Merry Christmas, dos Ramones, e Bodies, do Sex Pistols); um remix de Puteiro em João Pessoa e quatro canções gravadas ao vivo, quando a banda se apresentou no festival Hollywood Rock de 1996, no Rio de Janeiro. \\nUma versão da canção How Will I Laugh Tomorrow, da banda Suicidal Tendencies, foi gravada à época, porém, excluída do álbum, por não agradar ao Raimundos.',
        copies_sold: null,
        studio_id:9,
      },
      {
        name: 'Lapadas do Povo',
        release_date: 1997,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/d/d4/LapadasDoPovo.jpg/220px-LapadasDoPovo.jpg',
        about: 'Lapadas do Povo é o quarto álbum de estúdio da banda brasileira de punk rock, Raimundos. Lançado originalmente em 1997, e produzido por Mark Dearnley.',
        copies_sold: null,
        studio_id:9,
      },
      {
        name: 'Só no Forévis',
        release_date: 1999,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/1/1e/SoNoForevis.jpg/220px-SoNoForevis.jpg',
        about: 'Só no Forevis é o quinto álbum de estúdio da banda de rock brasileira Raimundos, lançado em 27 de maio de 1999.[1] Foi o disco de maior vendagem da banda, bem como o último com o vocalista Rodolfo Abrantes. O título é uma homenagem aos bordões do humorista Mussum dos Trapalhões (forevis é um sinônimo para "furébis" ou "nádegas"), que morreu em 1994.',
        copies_sold: null,
        studio_id:9,
      },
      {
        name: 'Éramos 4',
        release_date: 2001,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/e/e8/Raimundos_-_%C3%89ramos_4_-_2001.jpg/220px-Raimundos_-_%C3%89ramos_4_-_2001.jpg',
        about: 'Éramos 4 é o sexto álbum de estúdio da banda Raimundos, lançado em 2001, logo após a saída do vocalista Rodolfo Abrantes. O repertório do disco é basicamente formado por covers da banda Ramones, executados em um show de aniversário da rádio paulista 89 FM, com a patricipação de Marky Ramone, ex-baterista do grupo. \\nO disco ainda contém as canções "Nana Neném", gravada para uma campanha publicitária das sandálias Rider (Grendene) em 1998; "Desculpe, Mas Eu Vou Chorar", canção da dupla sertaneja Leandro & Leonardo, gravada em 1993; e "Sanidade", canção que fazia parte da primeira fita demo da banda, porém, seria apenas registrada oito anos depois, tendo no vocal principal o guitarrista Digão. \\nApesar do leve sarcasmo, o título do CD (sátira ao título do romance Éramos Seis, da escritora Maria José Dupré) transmite certa nostalgia aos fãs da banda, abalados com a saída de Rodolfo, que converteu-se à religião evangélica.',
        copies_sold: null,
        studio_id:9,
      },
      {
        name: 'Kavookavala',
        release_date: 2002,
        cover: 'https://images.uncyc.org/pt/thumb/c/c2/Kavookavala.jpg/300px-Kavookavala.jpg',
        about: 'Kavookavala é o sétimo álbum de estúdio da banda Raimundos, com Digão assumindo o posto de vocalista, deixado por Rodolfo Abrantes. Foi gravado no Rio de Janeiro. Há participação do cantor Derrick Green, da banda Sepultura na canção Kavookavala e do funkeiro Mr. Catra na musica Pegamutukala.Foram gravados dois videoclipes, um para a canção Fique Fique e o outro para Joey. O álbum teve uma vendagem melhor que o anterior, e apresenta sucessos como, "Fique! Fique!" e "Mas Vó".',
        copies_sold: null,
        studio_id:9,
      },
      {
        name: 'Cantigas de Roda',
        release_date: 2014,
        cover: 'https://3.bp.blogspot.com/-bmR6u7Pmd5k/U2D1recOM4I/AAAAAAAA4SY/y7wZkOGq_8A/s1600/Capa.jpg',
        about: 'Cantigas de Roda é o oitavo álbum de estúdio do Raimundos. Este é o primeiro álbum composto exclusivamente por músicas inéditas desde Kavookavala, lançado em 2002. Trabalhando até então de forma totalmente independente, a banda decidiu realizar um crowdfunding para financiar a gravação do disco, as recompensas para quem apoiasse o projeto iam desde o download antecipado do CD até a participação em clipe e ingressos para shows com direito a visita ao camarim. Somente os apoiadores teriam direito de receber o CD físico, uma vez que seriam produzidas somente 3 mil cópias do CD e cerca de 300 cópias em vinil. O disco foi gravado e produzido por Billy Graziadei, vocalista do Biohazard, e gravado no seu estúdio em Los Angeles, o Firewater Studios.',
        copies_sold: null,
        studio_id:2,
      },
      {
        name: 'Pt qQ coizah',
        release_date: 2005,
        cover: 'https://img.discogs.com/JE6dUI1NxVivRVmagubbp6QMBk4=/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-8290455-1458741151-9926.jpeg.jpg',
        about: 'No Registry',
        copies_sold: null,
        studio_id:2,
      },
      {
        name: 'MTV Ao Vivo CD',
        release_date: 2000,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/f/f8/Raimundos_-_MTV_ao_Vivo_-_2000.jpg/220px-Raimundos_-_MTV_ao_Vivo_-_2000.jpg',
        about: 'MTV ao vivo é o sexto álbum e primeiro trabalho ao vivo da banda brasileira de hardcore punk Raimundos, lançado em 2000. Foi também o primeiro álbum da série MTV ao Vivo. \nGravado em oito shows da turnê Só no Forévis nas cidades de São Paulo e Curitiba, o álbum é um apanhado geral da carreira da banda, devido a seu vasto repertório formado por sucessos como \'Mulher de Fases\', \'Tora-Tora\', \'Puteiro em João Pessoa\', \'Papeau Nuky Doe\' (única canção oriunda do álbum especial Cesta Básica), \'Eu Quero Ver o Oco\', \'Andar na Pedra\' e \'Esporrei na Manivela\', além da inédita \'Reggae do Manero\'. Como faixa-bônus, o CD inclui uma regravação em estúdio de \'20 e Poucos Anos\', sucesso do cantor Fábio Jr., utilizada também como tema do programa de mesmo nome da MTV Brasil.',
        copies_sold: null,
        studio_id:9,
      },
      {
        name: 'Roda Viva',
        release_date: 2011,
        cover: 'https://upload.wikimedia.org/wikipedia/pt/thumb/2/2a/Rodaviva.jpeg/220px-Rodaviva.jpeg',
        about: 'Roda Viva é um álbum ao vivo da banda brasileira Raimundos, é o segundo álbum ao vivo da banda. Roda Viva foi gravado no Kazebre Rock Bar em Dezembro/2010 com o público de 15 mil pessoas embalados pelo sucessos da banda. O álbum contém grandes sucessos da banda em 20 anos de carreira, e a inédita JAWS. \\nTodas as músicas escolhidas da época da formação com Rodolfo Abrantes tiveram participação de Digão e/ou Canisso, com exceção de "I Saw You Saying (That Say That You Saw)" que foi composta, além do Rodolfo, por Gabriel Thomaz (Little Quail/Autoramas, amigo pessoal e antigo letrista da banda)',
        copies_sold: null,
        studio_id:10,
      },
      {
        name: 'Cantigas de Garagem',
        release_date: 2014,
        cover: 'https://images-na.ssl-images-amazon.com/images/I/912QVQPqOzL._AC_SL1500_.jpg',
        about: 'Cantigas de Garagem é um álbum ao vivo da banda brasileira Raimundos. É o primeiro lançamento do grupo pela Som Livre. Terceiro registro ao vivo em vídeo da banda, Cantigas de Garagem diferencia-se por não ser uma gravação de show, e sim de um ensaio fechado do quarteto, no Nacena Studios, em São Paulo. A apresentação consiste-se no último álbum de estúdio, Cantigas de Roda, na íntegra, além de cinco regravações: quatro da fase com Rodolfo Abrantes nos vocais e uma da fase com Digão. O disco marca a volta do Raimundos para uma gravadora de peso, a Som Livre e, até então, é o único lançamento físico comercial onde as músicas do álbum Cantigas de Roda podem ser encontradas, visto que este só recebeu uma tiragem limitada para apoiadores do crowdfunding. \\nDiferentemente dos últimos trabalhos da banda (Roda Viva e Cantigas de Roda), Cantigas de Garagem foi anunciado ao público apenas 6 dias antes de seu lançamento em veículos de streaming. Para promover o álbum, no entanto, o site da Multishow exibiu durante 24 horas (meio-dia de 17 a 18 de novembro de 2014) o DVD na íntegra. \\nAssim como no álbum de estúdio que originou as canções, há participações especiais de Frango, da banda Galinha Preta, do rapper Cipriano e do rapper Sen Dog do grupo estadounidense Cypress Hill - este último, no entanto, apenas digitalmente.',
        copies_sold: null,
        studio_id:11,
      },
      {
        name: 'Raimundos Acústico',
        release_date: 2017,
        cover: 'https://images-americanas.b2w.io/produtos/01/00/sku/24101/6/24101625_1GG.jpg',
        about: 'Raimundos Acústico é um álbum ao vivo da banda brasileira de rock Raimundos, lançado em CD e DVD em abril de 2017 pela Som Livre. Gravado ao vivo e em formato acústico, trata-se do 4º álbum ao vivo da banda (o primeiro em formato acústico), e o 13º álbum de sua discografia. \\nGravado ao vivo no Teatro Positivo, em Curitiba (Paraná), nos dias 17 e 18 de novembro de 2016 para cerca de 4.000 espectadores de todas as idades, o show traz versões acústicas de sucessos consagrados de várias fases da banda, desde clássicos como "Esporrei na Manivela", "Eu Quero Ver o Oco" e "Mulher de Fases", até hits recentes, como "Gordelícia", "Baculejo" e "Dubmundos", em arranjos que contam com a presença de violinos, cellos, teclado, piano, acordeão, percussão e metais. Destaca-se ainda uma regravação de "Lugar ao Sol", da banda Charlie Brown Jr. Falando em Charlie Brown Jr., o guitarrista Marcão é um dos músicos convidados que participam de todo o álbum, e que acompanhou o quarteto durante a turnê de divulgação.',
        copies_sold: null,
        studio_id:11,
      }

     ])

  }
}

module.exports = AlbumSeeder
