'use strict'

/*
|--------------------------------------------------------------------------
| CountrySeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use('Factory')
const Country = use('App/Models/Country')

class CountrySeeder {
  async run () {
    await Country.createMany([
      {name: 'Afghanistan'},
      {name: 'Albania'},
      {name: 'Algeria'},
      {name: 'Andorra'},
      {name: 'Angola'},
      {name: 'Argentina'},
      {name: 'Armenia'},
      {name: 'Australia'},
      {name: 'Austria'},
      {name: 'Azerbaijan'},
      {name: 'Bahamas'},
      {name: 'Bahrain'},
      {name: 'Bangladesh'},
      {name: 'Barbados'},
      {name: 'Belarus'},
      {name: 'Belgium'},
      {name: 'Belize'},
      {name: 'Benin'},
      {name: 'Bhutan '},
      {name: 'Bolivia'},
      {name: 'Bosnia-Herzegovina'},
      {name: 'Botswana'},
      {name: 'Brazil'},
      {name: 'Brunei'},
      {name: 'Bulgaria'},
      {name: 'Burkina'},
      {name: 'Burma'},
      {name: 'Burundi'},
      {name: 'Cambodia'},
      {name: 'Cameroon'},
      {name: 'Canada'},
      {name: 'Cape Verde Islands'},
      {name: 'Chad'},
      {name: 'Chile'},
      {name: 'China'},
      {name: 'Colombia'},
      {name: 'Congo '},
      {name: 'Costa Rica'},
      {name: 'Croatia '},
      {name: 'Cuba'},
      {name: 'Cyprus '},
      {name: 'Czech Republic'},
      {name: 'Denmark'},
      {name: 'Djibouti'},
      {name: 'Dominica'},
      {name: 'Dominican Republic'},
      {name: 'Ecuador'},
      {name: 'Egypt'},
      {name: 'El Salvador '},
      {name: 'England'},
      {name: 'Eritrea'},
      {name: 'Estonia'},
      {name: 'Ethiopia'},
      {name: 'Fiji'},
      {name: 'Finland '},
      {name: 'France'},
      {name: 'Gabon'},
      {name: 'Gambia '},
      {name: 'Georgia'},
      {name: 'Germany'},
      {name: 'Ghana'},
      {name: 'Great Britain'},
      {name: 'Greece'},
      {name: 'Grenada'},
      {name: 'Guatemala'},
      {name: 'Guinea'},
      {name: 'Guyana '},
      {name: 'Haiti'},
      {name: 'Holland'},
      {name: 'Honduras'},
      {name: 'Hungary'},
      {name: 'Iceland'},
      {name: 'India'},
      {name: 'Indonesia'},
      {name: 'Iran'},
      {name: 'Iraq'},
      {name: 'Ireland'},
      {name: 'Israel'},
      {name: 'Italy'},
      {name: 'Japan'},
      {name: 'Jordan'},
      {name: 'Kazakhstan'},
      {name: 'Kenya'},
      {name: 'Korea'},
      {name: 'Kuwait'},
      {name: 'Laos'},
      {name: 'Latvia'},
      {name: 'Lebanon'},
      {name: 'Liberia'},
      {name: 'Libya'},
      {name: 'Liechtenstein'},
      {name: 'Lithuania'},
      {name: 'Luxenbourg'},
      {name: 'Macedonia'},
      {name: 'Madasgascar'},
      {name: 'Malawi'},
      {name: 'Malaysia '},
      {name: 'Mali'},
      {name: 'Malta'},
      {name: 'Maldives'},
      {name: 'Mauritania'},
      {name: 'Mauritius'},
      {name: 'Mexico'},
      {name: 'Moldova'},
      {name: 'Monaco'},
      {name: 'Mongolia'},
      {name: 'Montenegro'},
      {name: 'Morocco'},
      {name: 'Mozambique'},
      {name: 'Namibia'},
      {name: 'New Zealand'},
      {name: 'Nicaragua'},
      {name: 'Niger'},
      {name: 'Nigeria'},
      {name: 'North Korea'},
      {name: 'Norway'},
      {name: 'Oman'},
      {name: 'Pakistan'},
      {name: 'Panama'},
      {name: 'Papua New Guinea'},
      {name: 'Paraguay '},
      {name: 'Peru'},
      {name: 'Philippines'},
      {name: 'Poland'},
      {name: 'Portugal'},
      {name: 'Puerto Rico'},
      {name: 'Qatar'},
      {name: 'Romania'},
      {name: 'Russia'},
      {name: 'Rwanda'},
      {name: 'Saudi Arabia'},
      {name: 'Scotland'},
      {name: 'Senegal'},
      {name: 'Serbia'},
      {name: 'Seychelles'},
      {name: 'Sierra Leone'},
      {name: 'Singapore'},
      {name: 'Slovakia'},
      {name: 'Slovenia'},
      {name: 'Solomon Islands'},
      {name: 'Somalia'},
      {name: 'South Africa'},
      {name: 'South Korea'},
      {name: 'Spain'},
      {name: 'Sri Lanka'},
      {name: 'Sudan'},
      {name: 'Suricountry'},
      {name: 'Swaziland'},
      {name: 'Sweden'},
      {name: 'Switzerland'},
      {name: 'Syria'},
      {name: 'Taiwan'},
      {name: 'Tanzania'},
      {name: 'Thailand'},
      {name: 'Togo'},
      {name: 'Trinidad and Tobago '},
      {name: 'Tunisia'},
      {name: 'Turkey'},
      {name: 'Turkmenistan '},
      {name: 'Tuvalu'},
      {name: 'Uganda'},
      {name: 'Ukraine'},
      {name: 'United Arab Emirates'},
      {name: 'United Kingdom (UK)'},
      {name: 'United States of America (USA)'},
      {name: 'Uruguay'},
      {name: 'Uzbekistan'},
      {name: 'Vanuatu'},
      {name: 'Vatican'},
      {name: 'Venezuela'},
      {name: 'Vietnam'},
      {name: 'Western'},
      {name: 'Yemen'},
      {name: 'Yugoslavia'},
      {name: 'Zaire'},
      {name: 'Zambia '},
      {name: 'Zimbabwe'}
    ])
  }
}

module.exports = CountrySeeder
