'use strict'

/*
|--------------------------------------------------------------------------
| GenreSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use('Factory')
const Genre = use('App/Models/Genre')

class GenreSeeder {
  async run () {
    await Genre.createMany([
      {name: "Acid rock"},
      {name: "Afro-punk"},
      {name: "Alternative country"},
      {name: "Alternative dance"},
      {name: "Alternative hip hop"},
      {name: "Alternative metal"},
      {name: "Alternative rock"},
      {name: "Americana music"},
      {name: "Anarcho-punk"},
      {name: "Anatolian rock"},
      {name: "Art punk"},
      {name: "Art rock"},
      {name: "Avant-garde metal"},
      {name: "Baroque pop"},
      {name: "Baggy"},
      {name: "Bandana thrash"},
      {name: "Beach music"},
      {name: "Beat music"},
      {name: "Bent edge"},
      {name: "Big beat"},
      {name: "Biker metal"},
      {name: "BisRock"},
      {name: "Blackgaze"},
      {name: "Blackened death metal"},
      {name: "Black metal"},
      {name: "Blues rock"},
      {name: "Boogie rock"},
      {name: "Brazilian thrash metal"},
      {name: "British folk rock"},
      {name: "Britpop"},
      {name: "Britpop Revival"},
      {name: "Canterbury sound"},
      {name: "Cello rock and cello metal"},
      {name: "Celtic punk"},
      {name: "Celtic metal"},
      {name: "Celtic rock"},
      {name: "Chicano rock"},
      {name: "Christian alternative rock"},
      {name: "Christian hardcore"},
      {name: "Christian metal"},
      {name: "Christian punk"},
      {name: "Christian rock"},
      {name: "Cock rock"},
      {name: "Coldwave"},
      {name: "College rock"},
      {name: "Comedy rock"},
      {name: "Country rock"},
      {name: "Cowpunk"},
      {name: "Crossover thrash"},
      {name: "Crunkcore"},
      {name: "Crust punk"},
      {name: "Dance-punk"},
      {name: "Dance-rock"},
      {name: "Dark cabaret"},
      {name: "Darkwave"},
      {name: "D-beat"},
      {name: "Death 'n' roll"},
      {name: "Deathcore"},
      {name: "Death-doom"},
      {name: "Deathgrind"},
      {name: "Death metal"},
      {name: "Deathrock"},
      {name: "Digital hardcore"},
      {name: "Djent"},
      {name: "Doom metal"},
      {name: "Dream pop"},
      {name: "Drone metal"},
      {name: "Dunedin sound"},
      {name: "Electroclash"},
      {name: "Electropunk"},
      {name: "Electronicore"},
      {name: "Electronic rock"},
      {name: "Emo"},
      {name: "Emo pop"},
      {name: "Emo revival"},
      {name: "Ethereal wave"},
      {name: "Experimental rock"},
      {name: "Extreme metal"},
      {name: "Flamenco rock"},
      {name: "Folk metal"},
      {name: "Folk punk"},
      {name: "Folk rock"},
      {name: "Funk metal"},
      {name: "Funk rock"},
      {name: "Garage punk"},
      {name: "Garage rock"},
      {name: "Geek rock"},
      {name: "Glam metal"},
      {name: "Glam punk"},
      {name: "Glam rock"},
      {name: "Goregrind"},
      {name: "Gothabilly"},
      {name: "Gothic metal"},
      {name: "Gothic rock"},
      {name: "Grebo"},
      {name: "Grindcore"},
      {name: "Grindie"},
      {name: "Groove metal"},
      {name: "Group Sounds"},
      {name: "Grunge"},
      {name: "Gypsy punk"},
      {name: "Hard rock"},
      {name: "Hardcore punk"},
      {name: "Heartland rock"},
      {name: "Heavy hardcore"},
      {name: "Heavy metal"},
      {name: "Horror punk"},
      {name: "Indie folk"},
      {name: "Indie pop"},
      {name: "Indie rock"},
      {name: "Indietronica"},
      {name: "Indorock"},
      {name: "Industrial metal"},
      {name: "Industrial rock"},
      {name: "Instrumental rock"},
      {name: "Italian occult psychedelia"},
      {name: "Jazz rock"},
      {name: "Jangle pop"},
      {name: "Jersey Shore sound"},
      {name: "Krautrock"},
      {name: "Kawaii metal"},
      {name: "Latin alternative"},
      {name: "Latin metal"},
      {name: "Latin rock"},
      {name: "Madchester"},
      {name: "Manila Sound"},
      {name: "Mathcore"},
      {name: "Math rock"},
      {name: "Medieval folk rock"},
      {name: "Medieval metal"},
      {name: "Melodic death metal"},
      {name: "Melodic hardcore"},
      {name: "Melodic metalcore"},
      {name: "Metalcore"},
      {name: "Mod revival"},
      {name: "Nardcore"},
      {name: "Neue Deutsche Härte"},
      {name: "Neue Deutsche Todeskunst"},
      {name: "Neue Deutsche Welle"},
      {name: "Neoclassical dark wave"},
      {name: "Neoclassical metal"},
      {name: "Neon pop"},
      {name: "Neo-progressive rock"},
      {name: "Neo-psychedelia"},
      {name: "New rave"},
      {name: "New wave"},
      {name: "New wave of new wave"},
      {name: "New Weird America"},
      {name: "Nintendocore"},
      {name: "Noise pop"},
      {name: "Noise rock"},
      {name: "No wave"},
      {name: "Nu gaze"},
      {name: "Nu metal"},
      {name: "Nu metalcore"},
      {name: "Occult rock"},
      {name: "Oi!"},
      {name: "Ostrock"},
      {name: "Outlaw Country"},
      {name: "Pagan metal"},
      {name: "Pagan rock"},
      {name: "Paisley Underground"},
      {name: "Peace punk"},
      {name: "Pinoy rock"},
      {name: "Pirate metal"},
      {name: "Pop punk"},
      {name: "Pop rock"},
      {name: "Pornogrind"},
      {name: "Post-britpop"},
      {name: "Post-grunge"},
      {name: "Post-hardcore"},
      {name: "Post-metal"},
      {name: "Post-punk"},
      {name: "Post-punk revival"},
      {name: "Post-rock"},
      {name: "Power pop"},
      {name: "Power metal"},
      {name: "Powerviolence"},
      {name: "Progressive metal"},
      {name: "Progressive metalcore"},
      {name: "Progressive rock"},
      {name: "Protopunk"},
      {name: "Psychedelic funk"},
      {name: "Psychedelic pop"},
      {name: "Psychedelic rock"},
      {name: "Psychobilly"},
      {name: "Pub rock (Australia)"},
      {name: "Pub rock (United Kingdom)"},
      {name: "Punk blues"},
      {name: "Punk jazz"},
      {name: "Punk rap"},
      {name: "Punk pathetique"},
      {name: "Punk rock"},
      {name: "Queercore"},
      {name: "Raga rock"},
      {name: "Rapcore"},
      {name: "Rap metal"},
      {name: "Rap rock"},
      {name: "Reggae rock"},
      {name: "Red dirt"},
      {name: "Riot grrrl"},
      {name: "Rock Against Communism"},
      {name: "Rock and roll"},
      {name: "Rockabilly"},
      {name: "Rock in Opposition"},
      {name: "Roots rock"},
      {name: "Sadcore"},
      {name: "Samba rock"},
      {name: "Screamo"},
      {name: "Shoegazing"},
      {name: "Shock rock"},
      {name: "Ska punk"},
      {name: "Skate punk"},
      {name: "Slowcore"},
      {name: "Sludge metal"},
      {name: "Soft rock"},
      {name: "Southern rock"},
      {name: "Space rock"},
      {name: "Speed metal"},
      {name: "Straight edge"},
      {name: "Stoner rock"},
      {name: "Street punk"},
      {name: "Sufi rock"},
      {name: "Sunshine pop"},
      {name: "Surf music"},
      {name: "Swamp pop"},
      {name: "Swedish death metal"},
      {name: "Symphonic black metal"},
      {name: "Symphonic metal"},
      {name: "Synthpop"},
      {name: "Taqwacore"},
      {name: "Technical death metal"},
      {name: "Thrashcore"},
      {name: "Thrash metal"},
      {name: "Trall punk"},
      {name: "Trap metal"},
      {name: "Trønder rock"},
      {name: "Tropical rock"},
      {name: "Tulsa Sound"},
      {name: "2 Tone"},
      {name: "Unblack metal"},
      {name: "Forrócore"}
    ])
  }
}

module.exports = GenreSeeder
