'use strict'

/*
|--------------------------------------------------------------------------
| TrackSeeder
|--------------------------------------------------------------------------
|
| Make use of the Factory instance to seed database with dummy data or
| make use of Lucid models directly.
|
*/

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use('Factory')
const Track = use('App/models/Track')

class TrackSeeder {
  async run () {
    await Track.createMany([

      {
        track_number:1,
        title: 'Dia Corrido',
        track_duration: '00:02:55',
        album_id:1,
      },
      {
        track_number:2,
        title: 'Amigos Valem Mais do Que Asfalto',
        track_duration: '00:04:14',
        album_id:1,
      },
      {
        track_number:3,
        title: 'Máquina do Tempo',
        track_duration: '00:02:11',
        album_id:1,
      },
      {
        track_number:4,
        title: 'O Homem do Centro da Cidade',
        track_duration: '00:02:53',
        album_id:1,
      },
      {
        track_number:5,
        title: 'O Mundo É Dos Espertos',
        track_duration: '00:03:19',
        album_id:1,
      },
      {
        track_number:6,
        title: 'Vida Urbana',
        track_duration: '00:03:04',
        album_id:1,
      },
      {
        track_number:7,
        title: 'Espelho da Alma',
        track_duration: '00:04:07',
        album_id:1,
      },
      {
        track_number:8,
        title: 'Redenção',
        track_duration: '00:04:24',
        album_id:1,
      },
      {
        track_number:9,
        title: 'Coragem',
        track_duration: '00:03:03',
        album_id:1,
      },
      {
        track_number:10,
        title: 'O Rebelde Virtual',
        track_duration: '00:02:10',
        album_id:1,
      },
      {
        track_number:11,
        title: 'Não, Nós Não Somos Originais',
        track_duration: '00:04:53',
        album_id:1,
      },
      {
        track_number:12,
        title: 'Eu Prometo Que Vou Tentar',
        track_duration: '00:04:32',
        album_id:1,
      },
      {
        track_number:1,
        title: 'Voltar a Ser',
        track_duration: '00:04:26',
        album_id:5,
      },
      {
        track_number:2,
        title: 'Reencontro',
        track_duration: '00:03:52',
        album_id:5,
      },
      {
        track_number:3,
        title: 'O Fago',
        track_duration: '00:03:39',
        album_id:5,
      },
      {
        track_number:4,
        title: 'Próprios Passos',
        track_duration: '00:03:22',
        album_id:5,
      },
      {
        track_number:5,
        title: 'Tentar Esquecer',
        track_duration: '00:04:09',
        album_id:5,
      },
      {
        track_number:6,
        title: 'Problemas',
        track_duration: '00:03:22',
        album_id:5,
      },
      {
        track_number:7,
        title: 'Adeus',
        track_duration: '00:04:37',
        album_id:5,
      },
      {
        track_number:8,
        title: 'Silêncio',
        track_duration: '00:03:57',
        album_id:5,
      },
      {
        track_number:9,
        title: 'Ultima Vez',
        track_duration: '00:03:55',
        album_id:5,
      },
      {
        track_number:10,
        title: 'Amanhecer',
        track_duration: '00:03:41',
        album_id:5,
      },
      {
        track_number:11,
        title: '17 Anos',
        track_duration: '00:02:01',
        album_id:5,
      },
      {
        track_number:12,
        title: 'Novo Dia',
        track_duration: '00:03:26',
        album_id:5,
      },
      {
        track_number:13,
        title: 'Lados_opostos',
        track_duration: '00:03:07',
        album_id:5,
      },
      {
        track_number:1,
        title: 'Contra-cultura',
        track_duration: '00:03:46',
        album_id:2,
      },
      {
        track_number:2,
        title: 'Aponte pro espelho',
        track_duration: '00:02:33',
        album_id:2,
      },
      {
        track_number:3,
        title: 'Gota a gota',
        track_duration: '00:02:25',
        album_id:2,
      },
      {
        track_number:4,
        title: 'Andando sobre pedras',
        track_duration: '00:03:56',
        album_id:2,
      },
      {
        track_number:5,
        title: 'Falta',
        track_duration: '00:02:51',
        album_id:2,
      },
      {
        track_number:6,
        title: 'O que me cega',
        track_duration: '00:03:23',
        album_id:2,
      },
      {
        track_number:7,
        title: 'Ismos',
        track_duration: '00:02:32',
        album_id:2,
      },
      {
        track_number:8,
        title: 'Paciência',
        track_duration: '00:02:40',
        album_id:2,
      },
      {
        track_number:9,
        title: 'Seguro demais',
        track_duration: '00:03:04',
        album_id:2,
      },
      {
        track_number:10,
        title: 'Expansão da consciência',
        track_duration: '00:03:27',
        album_id:2,
      },
      {
        track_number:1,
        title: 'Intro (Ao Vivo)',
        track_duration: '00:01:58',
        album_id:3,
      },
      {
        track_number:2,
        title: 'Dia Corrido (Ao Vivo)',
        track_duration: '00:02:53',
        album_id:3,
      },
      {
        track_number:3,
        title: 'Expansão da Consciência (Ao Vivo)',
        track_duration: '00:03:29',
        album_id:3,
      },
      {
        track_number:4,
        title: 'Amigos Valem Mais do Que Asfalto (Ao Vivo)',
        track_duration: '00:04:03',
        album_id:3,
      },
      {
        track_number:5,
        title: 'Máquina do Tempo (Ao vivo)',
        track_duration: '00:02:09',
        album_id:3,
      },
      {
        track_number:6,
        title: 'Aponte Para o Espelho (Ao Vivo)',
        track_duration: '00:03:08',
        album_id:3,
      },
      {
        track_number:7,
        title: 'O Que Me Cega (Ao Vivo)',
        track_duration: '00:03:29',
        album_id:3,
      },
      {
        track_number:8,
        title: 'Não, Nós Não Somos Originais (Ao Vivo)',
        track_duration: '00:04:49',
        album_id:3,
      },
      {
        track_number:9,
        title: 'Espelho da Alma (Ao Vivo)',
        track_duration: '00:03:59',
        album_id:3,
      },
      {
        track_number:10,
        title: 'O Mundo é dos Espertos (Ao Vivo)',
        track_duration: '00:03:17',
        album_id:3,
      },
      {
        track_number:11,
        title: 'Falta (Ao Vivo)',
        track_duration: '00:02:50',
        album_id:3,
      },
      {
        track_number:12,
        title: 'Andando Sobre Pedras (Ao Vivo)',
        track_duration: '00:04:02',
        album_id:3,
      },
      {
        track_number:13,
        title: 'Eu Prometo Que Vou Tentar (Ao Vivo)',
        track_duration: '00:04:38',
        album_id:3,
      },
      {
        track_number:14,
        title: 'Seguro Demais (Ao Vivo)',
        track_duration: '00:03:08',
        album_id:3,
      },
      {
        track_number:15,
        title: 'Gota a Gota (Ao Vivo)',
        track_duration: '00:02:37',
        album_id:3,
      },
      {
        track_number:16,
        title: 'Contra Cultura (Ao Vivo)',
        track_duration: '00:04:55',
        album_id:3,
      },
      {
        track_number:1,
        title: 'Intro (Eduardo Galeano)',
        track_duration: '00:00:20',
        album_id:4,
      },
      {
        track_number:2,
        title: 'Utopia',
        track_duration: '00:03:13',
        album_id:4,
      },
      {
        track_number:3,
        title: 'Corpo, mente, espírito',
        track_duration: '00:03:04',
        album_id:4,
      },
      {
        track_number:4,
        title: 'Levanta e vai',
        track_duration: '00:02:59',
        album_id:4,
      },
      {
        track_number:5,
        title: 'Existência',
        track_duration: '00:03:12',
        album_id:4,
      },
      {
        track_number:6,
        title: 'Matrix',
        track_duration: '00:02:39',
        album_id:4,
      },
      {
        track_number:7,
        title: 'Do que sou',
        track_duration: '00:03:13',
        album_id:4,
      },
      {
        track_number:8,
        title: 'Eu não posso mais',
        track_duration: '00:02:49',
        album_id:4,
      },
      {
        track_number:9,
        title: 'Você sabe com quem está falando',
        track_duration: '00:03:26',
        album_id:4,
      },
      {
        track_number:10,
        title: 'Todo momento é o agora',
        track_duration: '00:03:37',
        album_id:4,
      },
      {
        track_number:11,
        title: 'Revitalizar',
        track_duration: '00:03:11',
        album_id:4,
      },
      {
        track_number:1,
        title: 'Projeto Inacabado',
        track_duration: '00:03:04',
        album_id:6,
      },
      {
        track_number:2,
        title: 'O Único a Me Machucar',
        track_duration: '00:04:31',
        album_id:6,
      },
      {
        track_number:3,
        title: 'Lembrar Me Faz Sofrer',
        track_duration: '00:02:48',
        album_id:6,
      },
      {
        track_number:4,
        title: 'Agora Eu Sei',
        track_duration: '00:03:34',
        album_id:6,
      },
      {
        track_number:5,
        title: 'Dentro dos Seus Olhos',
        track_duration: '00:03:31',
        album_id:6,
      },
      {
        track_number:6,
        title: 'Sentimento Algum',
        track_duration: '00:04:43',
        album_id:6,
      },
      {
        track_number:7,
        title: 'Prestes a Morrer',
        track_duration: '00:03:21',
        album_id:6,
      },
      {
        track_number:8,
        title: 'Paz',
        track_duration: '00:03:48',
        album_id:6,
      },
      {
        track_number:9,
        title: 'Ainda é Cedo',
        track_duration: '00:03:34',
        album_id:6,
      },
      {
        track_number:10,
        title: 'Um Dia Pra Sonhar',
        track_duration: '00:04:33',
        album_id:6,
      },
      {
        track_number:11,
        title: 'Buscando a Razão',
        track_duration: '00:03:04',
        album_id:6,
      },
      {
        track_number:12,
        title: 'Foi-se o Tempo',
        track_duration: '00:02:57',
        album_id:6,
      },
      {
        track_number:13,
        title: 'Não Volte Mais',
        track_duration: '00:02:54',
        album_id:6,
      },
      {
        track_number:1,
        title: 'A Marcha do Mundo',
        track_duration: '00:03:14',
        album_id:7,
      },
      {
        track_number:2,
        title: 'Arqui-inimigo',
        track_duration: '00:03:44',
        album_id:7,
      },
      {
        track_number:3,
        title: 'Desapareceu',
        track_duration: '00:03:43',
        album_id:7,
      },
      {
        track_number:4,
        title: 'Distância',
        track_duration: '00:02:38',
        album_id:7,
      },
      {
        track_number:5,
        title: 'Duas Caras',
        track_duration: '00:03:47',
        album_id:7,
      },
      {
        track_number:1,
        title: 'Acrofobia',
        track_duration: '00:03:40',
        album_id:8,
      },
      {
        track_number:2,
        title: 'Renova',
        track_duration: '00:03:12',
        album_id:8,
      },
      {
        track_number:3,
        title: 'Viver',
        track_duration: '00:03:40',
        album_id:8,
      },
      {
        track_number:4,
        title: 'Guerra',
        track_duration: '00:03:01',
        album_id:8,
      },
      {
        track_number:5,
        title: 'Círculo Plano',
        track_duration: '00:02:26',
        album_id:8,
      },
      {
        track_number:1,
        title: 'Por Entre os Dedos',
        track_duration: '00:03:55',
        album_id:9,
      },
      {
        track_number:2,
        title: 'Horizontal',
        track_duration: '00:03:37',
        album_id:9,
      },
      {
        track_number:3,
        title: 'Telas',
        track_duration: '00:04:22',
        album_id:9,
      },
      {
        track_number:4,
        title: 'Overview Effect',
        track_duration: '00:04:08',
        album_id:9,
      },
      {
        track_number:5,
        title: 'Sob o Mesmo Sol',
        track_duration: '00:03:27',
        album_id:9,
      },
      {
        track_number:6,
        title: 'Dormência',
        track_duration: '00:03:45',
        album_id:9,
      },
      {
        track_number:7,
        title: 'Ranhura',
        track_duration: '00:01:13',
        album_id:9,
      },
      {
        track_number:8,
        title: 'Norte',
        track_duration: '00:03:41',
        album_id:9,
      },
      {
        track_number:9,
        title: 'Estado Surdo da Memória',
        track_duration: '00:03:48',
        album_id:9,
      },
      {
        track_number:10,
        title: 'Conselho de Quem Já Esteve Lá',
        track_duration: '00:04:00',
        album_id:9,
      },
      {
        track_number:11,
        title: 'De São Paulo a Xangai',
        track_duration: '00:03:18',
        album_id:9,
      },
      {
        track_number:12,
        title: 'O Sonho É uma Ilha',
        track_duration: '00:05:54',
        album_id:9,
      },
      {
        track_number:1,
        title: 'Norte',
        track_duration: '00:03:40',
        album_id:10,
      },
      {
        track_number:2,
        title: 'Norte - Acústico',
        track_duration: '00:03:58',
        album_id:10,
      },
      {
        track_number:1,
        title: 'Retrógrado',
        track_duration: '00:00:53',
        album_id:11,
      },
      {
        track_number:2,
        title: 'Fim do Dia',
        track_duration: '00:04:16',
        album_id:11,
      },
      {
        track_number:3,
        title: 'Peso da Verdade',
        track_duration: '00:04:24',
        album_id:11,
      },
      {
        track_number:4,
        title: 'O Sangue Que Te Cega',
        track_duration: '00:04:47',
        album_id:11,
      },
      {
        track_number:5,
        title: 'Desconforme',
        track_duration: '00:04:42',
        album_id:11,
      },
      {
        track_number:6,
        title: 'Constante',
        track_duration: '00:05:17',
        album_id:11,
      },
      {
        track_number:1,
        title: 'Brilho',
        track_duration: '00:01:47',
        album_id:12,
      },
      {
        track_number:2,
        title: 'Existência Seca',
        track_duration: '00:04:07',
        album_id:12,
      },
      {
        track_number:3,
        title: 'Nítido',
        track_duration: '00:03:45',
        album_id:12,
      },
      {
        track_number:4,
        title: 'Clarão',
        track_duration: '00:05:08',
        album_id:12,
      },
      {
        track_number:5,
        title: 'Ponto Nulo no Céu',
        track_duration: '00:04:30',
        album_id:12,
      },
      {
        track_number:6,
        title: 'Penumbra',
        track_duration: '00:04:08',
        album_id:12,
      },
      {
        track_number:7,
        title: 'Subsolo',
        track_duration: '00:04:11',
        album_id:12,
      },
      {
        track_number:8,
        title: 'Sem Dor, Sem Vida',
        track_duration: '00:04:35',
        album_id:12,
      },
      {
        track_number:9,
        title: '5-45',
        track_duration: '00:02:54',
        album_id:12,
      },
      {
        track_number:10,
        title: 'Peito Aberto',
        track_duration: '00:04:51',
        album_id:12,
      },
      {
        track_number:11,
        title: 'Sopro',
        track_duration: '00:03:23',
        album_id:12,
      },
      {
        track_number:12,
        title: 'Na Sombra do Ego',
        track_duration: '00:04:50',
        album_id:12,
      },
      {
        track_number:13,
        title: '(R)Evolução Mental',
        track_duration: '00:04:36',
        album_id:12,
      },
      {
        track_number:1,
        title: 'Tributo ao Frango da Malásia (Instrumental)',
        track_duration: '00:00:25',
        album_id:13,
      },
      {
        track_number:2,
        title: 'O Coro Vai Comê!',
        track_duration: '00:02:21',
        album_id:13,
      },
      {
        track_number:3,
        title: 'Tudo que Ela Gosta de Escutar',
        track_duration: '00:02:56',
        album_id:13,
      },
      {
        track_number:4,
        title: 'Sheik',
        track_duration: '00:02:51',
        album_id:13,
      },
      {
        track_number:5,
        title: 'Hei! Arreia... (Instrumental)',
        track_duration: '00:00:26',
        album_id:13,
      },
      {
        track_number:6,
        title: 'Gimme o anel',
        track_duration: '00:02:50',
        album_id:13,
      },
      {
        track_number:7,
        title: 'Molengol´s Groove (Instrumental)',
        track_duration: '00:00:53',
        album_id:13,
      },
      {
        track_number:8,
        title: 'Aquela Paz',
        track_duration: '00:03:02',
        album_id:13,
      },
      {
        track_number:9,
        title: 'Quinta-Feira',
        track_duration: '00:04:50',
        album_id:13,
      },
      {
        track_number:10,
        title: 'Proibida pra Mim (Grazon)',
        track_duration: '00:02:48',
        album_id:13,
      },
      {
        track_number:11,
        title: 'Lombra',
        track_duration: '00:03:11',
        album_id:13,
      },
      {
        track_number:12,
        title: 'Corra Vagabundo',
        track_duration: '00:03:35',
        album_id:13,
      },
      {
        track_number:13,
        title: 'Falar, falar...',
        track_duration: '00:02:47',
        album_id:13,
      },
      {
        track_number:14,
        title: 'Festa',
        track_duration: '00:02:51',
        album_id:13,
      },
      {
        track_number:15,
        title: 'Escalas Tropicais (Part. Lagoa 66)',
        track_duration: '00:02:08',
        album_id:13,
      },
      {
        track_number:16,
        title: 'Charlie Brown Jr. (Deixa Estar Que Eu Sigo Em Frente)',
        track_duration: '00:03:12',
        album_id:13,
      },
      {
        track_number:1,
        title: 'Confisco',
        track_duration: '00:03:00',
        album_id:14,
      },
      {
        track_number:2,
        title: 'Zóio de Lula',
        track_duration: '00:04:12',
        album_id:14,
      },
      {
        track_number:3,
        title: 'Resolve o Meu Problema Aí',
        track_duration: '00:02:59',
        album_id:14,
      },
      {
        track_number:4,
        title: 'Te Levar',
        track_duration: '00:03:04',
        album_id:14,
      },
      {
        track_number:5,
        title: 'Vinheta: O Que é da Casa, é da Casa',
        track_duration: '00:01:01',
        album_id:14,
      },
      {
        track_number:6,
        title: 'O Preço',
        track_duration: '00:03:30',
        album_id:14,
      },
      {
        track_number:7,
        title: 'Não Deixe O Mar Te Engolir',
        track_duration: '00:05:09',
        album_id:14,
      },
      {
        track_number:8,
        title: 'Hoje de Noite',
        track_duration: '00:02:41',
        album_id:14,
      },
      {
        track_number:9,
        title: 'Bons Aliados (part. Raimundos)',
        track_duration: '00:02:24',
        album_id:14,
      },
      {
        track_number:10,
        title: 'Puxa Carro',
        track_duration: '00:02:53',
        album_id:14,
      },
      {
        track_number:11,
        title: 'Vinheta: União (part. Radjja de Santos, De Menos Crime, Homens Crânio e Consciência Humana)',
        track_duration: '00:02:59',
        album_id:14,
      },
      {
        track_number:12,
        title: 'Aquele Velho Carteado e Algumas Manobrinhas',
        track_duration: '00:02:35',
        album_id:14,
      },
      {
        track_number:13,
        title: '333',
        track_duration: '00:02:28',
        album_id:14,
      },
      {
        track_number:14,
        title: 'Mantenha a Dúvida',
        track_duration: '00:03:04',
        album_id:14,
      },
      {
        track_number:15,
        title: 'Do Surf (Instrumental)',
        track_duration: '00:01:55',
        album_id:14,
      },
      {
        track_number:16,
        title: 'História Mal Escrita',
        track_duration: '00:04:02',
        album_id:14,
      },
      {
        track_number:17,
        title: 'Chicanos (Skate Nos Canos)',
        track_duration: '00:01:24',
        album_id:14,
      },
      {
        track_number:18,
        title: 'A Grande Volta',
        track_duration: '00:02:29',
        album_id:14,
      },
      {
        track_number:19,
        title: 'Cruzei uma Doida',
        track_duration: '00:01:45',
        album_id:14,
      },
      {
        track_number:20,
        title: '12+1 (Doze Mais Um)',
        track_duration: '00:03:00',
        album_id:14,
      },
      {
        track_number:21,
        title: 'Cidade Grande',
        track_duration: '00:03:15',
        album_id:14,
      },
      {
        track_number:22,
        title: 'Local',
        track_duration: '00:02:10',
        album_id:14,
      },
      {
        track_number:23,
        title: 'Muito Antes que Você',
        track_duration: '00:02:28',
        album_id:14,
      },
      {
        track_number:24,
        title: 'Depois de uma Bela Session, Um Belo Sofá, Cerveja,Pizza e um Videozinho de SKT (Instrumental)',
        track_duration: '00:01:07',
        album_id:14,
      },
      {
        track_number:25,
        title: 'Deu Entrada pra Subir!',
        track_duration: '00:03:08',
        album_id:14,
      },
      {
        track_number:1,
        title: 'Rubão, o Dono do Mundo',
        track_duration: '00:02:17',
        album_id:15,
      },
      {
        track_number:2,
        title: 'Ralé',
        track_duration: '00:03:15',
        album_id:15,
      },
      {
        track_number:3,
        title: 'Não É Sério (part. Negra Li)',
        track_duration: '00:04:50',
        album_id:15,
      },
      {
        track_number:4,
        title: 'O Penetra',
        track_duration: '00:03:14',
        album_id:15,
      },
      {
        track_number:5,
        title: 'A Banca (part. Sabotage e RZO)',
        track_duration: '00:05:53',
        album_id:15,
      },
      {
        track_number:6,
        title: 'Tudo Mudar',
        track_duration: '00:02:13',
        album_id:15,
      },
      {
        track_number:7,
        title: 'Fichado',
        track_duration: '00:03:08',
        album_id:15,
      },
      {
        track_number:8,
        title: 'Ouviu-se Falar',
        track_duration: '00:03:12',
        album_id:15,
      },
      {
        track_number:9,
        title: 'Amor Pelas Ruas (Instrumental)',
        track_duration: '00:01:57',
        album_id:15,
      },
      {
        track_number:10,
        title: 'Essa é Por Quem Ficou pra Trás',
        track_duration: '00:03:37',
        album_id:15,
      },
      {
        track_number:11,
        title: 'Transar no Escuro',
        track_duration: '00:03:03',
        album_id:15,
      },
      {
        track_number:12,
        title: '"Fundão" (Vinheta)',
        track_duration: '00:01:57',
        album_id:15,
      },
      {
        track_number:13,
        title: 'Somos Extremes no Esporte e na Música (part. De Menos Crime e Controlamente)',
        track_duration: '00:04:31',
        album_id:15,
      },
      {
        track_number:14,
        title: 'Talvez a Metade do Caminho (part. Fabio Abrão)',
        track_duration: '00:03:01',
        album_id:15,
      },
      {
        track_number:15,
        title: 'Pra Mais Tarde Fazermos a Cabeça',
        track_duration: '00:03:01',
        album_id:15,
      },
      {
        track_number:16,
        title: 'No Desafio, Ibiraboys / A União Prevalece',
        track_duration: '00:03:50',
        album_id:15,
      },
      {
        track_number:17,
        title: 'Trocando uma Idéia com Deus',
        track_duration: '00:03:05',
        album_id:15,
      },
      {
        track_number:1,
        title: 'Eu Protesto',
        track_duration: '00:04:28',
        album_id:16,
      },
      {
        track_number:2,
        title: 'Hoje Eu Acordei Feliz',
        track_duration: '00:02:18',
        album_id:16,
      },
      {
        track_number:3,
        title: 'Sino Dourado',
        track_duration: '00:02:41',
        album_id:16,
      },
      {
        track_number:4,
        title: 'Quebra-Mar',
        track_duration: '00:02:57',
        album_id:16,
      },
      {
        track_number:5,
        title: 'Lugar Ao Sol',
        track_duration: '00:03:32',
        album_id:16,
      },
      {
        track_number:6,
        title: 'Descubra O Que Há De Errado Com Você',
        track_duration: '00:01:39',
        album_id:16,
      },
      {
        track_number:7,
        title: 'Só Lazer',
        track_duration: '00:02:58',
        album_id:16,
      },
      {
        track_number:8,
        title: 'Você Vai De Limusine, Eu Vou De Trem',
        track_duration: '00:02:57',
        album_id:16,
      },
      {
        track_number:9,
        title: 'O Lado Certo Da Vida Errada',
        track_duration: '00:01:49',
        album_id:16,
      },
      {
        track_number:10,
        title: 'T.F.D.P.',
        track_duration: '00:02:51',
        album_id:16,
      },
      {
        track_number:11,
        title: 'Tudo Pro Alto',
        track_duration: '00:03:23',
        album_id:16,
      },
      {
        track_number:12,
        title: 'Como Tudo Deve Ser',
        track_duration: '00:04:33',
        album_id:16,
      },
      {
        track_number:1,
        title: 'Papo Reto (Prazer É Sexo, o Resto É Negócio)',
        track_duration: '00:03:30',
        album_id:17,
      },
      {
        track_number:2,
        title: 'Hoje Eu Só Procuro a Minha Paz',
        track_duration: '00:04:12',
        album_id:17,
      },
      {
        track_number:3,
        title: 'Baader-Meinhof Blues (cover de Legião Urbana)',
        track_duration: '00:02:53',
        album_id:17,
      },
      {
        track_number:4,
        title: 'Só Por Uma Noite',
        track_duration: '00:03:23',
        album_id:17,
      },
      {
        track_number:5,
        title: 'My Mini Ramp',
        track_duration: '00:02:12',
        album_id:17,
      },
      {
        track_number:6,
        title: 'Bocas Ordinárias, Guerrilha',
        track_duration: '00:04:16',
        album_id:17,
      },
      {
        track_number:7,
        title: 'Não Fure os Olhos da Verdade',
        track_duration: '00:02:47',
        album_id:17,
      },
      {
        track_number:8,
        title: 'Sou Quem eu Sou (O Que é seu Também é Meu e o Que é Meu Não é Nosso)',
        track_duration: '00:03:19',
        album_id:17,
      },
      {
        track_number:9,
        title: 'Com Minha Loucura Faço Meu Dinheiro, Com Meu Dinheiro Faço Minhas Loucuras',
        track_duration: '00:02:28',
        album_id:17,
      },
      {
        track_number:10,
        title: 'Somos Poucos, Mas Somos Loucos',
        track_duration: '00:05:30',
        album_id:17,
      },
      {
        track_number:11,
        title: 'Com a Boca Amargando',
        track_duration: '00:05:04',
        album_id:17,
      },
      {
        track_number:12,
        title: 'Tarja Preta',
        track_duration: '00:02:46',
        album_id:17,
      },
      {
        track_number:1,
        title: 'Malabarizando (Quem é de Fé Continua com a Gente)',
        track_duration: '00:01:40',
        album_id:18,
      },
      {
        track_number:2,
        title: 'Champanhe e Água Benta',
        track_duration: '00:02:31',
        album_id:18,
      },
      {
        track_number:3,
        title: 'Tamo Aí na Atividade',
        track_duration: '00:03:39',
        album_id:18,
      },
      {
        track_number:4,
        title: 'Eu Vim de Santos, Sou Charlie Brown',
        track_duration: '00:04:06',
        album_id:18,
      },
      {
        track_number:5,
        title: 'So Far Away',
        track_duration: '00:02:21',
        album_id:18,
      },
      {
        track_number:6,
        title: 'Longe de Você',
        track_duration: '00:03:22',
        album_id:18,
      },
      {
        track_number:7,
        title: 'Di-SK8 eu Vim',
        track_duration: '00:01:18',
        album_id:18,
      },
      {
        track_number:8,
        title: 'Di-SK8 eu Vou',
        track_duration: '00:03:21',
        album_id:18,
      },
      {
        track_number:9,
        title: 'Vivendo Nesse Absurdo',
        track_duration: '00:04:33',
        album_id:18,
      },
      {
        track_number:10,
        title: 'Todos Iguais',
        track_duration: '00:04:03',
        album_id:18,
      },
      {
        track_number:11,
        title: 'Cheirando Cola',
        track_duration: '00:01:34',
        album_id:18,
      },
      {
        track_number:12,
        title: 'O Errado que deu Certo',
        track_duration: '00:02:50',
        album_id:18,
      },
      {
        track_number:13,
        title: 'Malokero SK8 Board',
        track_duration: '00:02:09',
        album_id:18,
      },
      {
        track_number:14,
        title: 'Indicados para o Prêmio Nobel da Paz',
        track_duration: '00:02:06',
        album_id:18,
      },
      {
        track_number:15,
        title: 'O Lixo e o Luxo',
        track_duration: '00:02:43',
        album_id:18,
      },
      {
        track_number:1,
        title: 'Too Fast to Live, Too Young to Die',
        track_duration: '00:00:39',
        album_id:19,
      },
      {
        track_number:2,
        title: 'No Passo a Passo',
        track_duration: '00:02:27',
        album_id:19,
      },
      {
        track_number:3,
        title: 'Lutar pelo Que É Meu',
        track_duration: '00:03:20',
        album_id:19,
      },
      {
        track_number:4,
        title: 'É Quente',
        track_duration: '00:02:58',
        album_id:19,
      },
      {
        track_number:5,
        title: 'Onde Não Existe a Paz, Não Existe o Amor',
        track_duration: '00:04:07',
        album_id:19,
      },
      {
        track_number:6,
        title: 'Ela Vai Voltar (Todos os Defeitos de Uma Mulher Perfeita)',
        track_duration: '00:03:07',
        album_id:19,
      },
      {
        track_number:7,
        title: 'O Mundo Explodiu Lá Fora',
        track_duration: '00:03:00',
        album_id:19,
      },
      {
        track_number:8,
        title: 'Senhor do Tempo',
        track_duration: '00:03:22',
        album_id:19,
      },
      {
        track_number:9,
        title: 'Liberdade Acima de Tudo',
        track_duration: '00:03:07',
        album_id:19,
      },
      {
        track_number:10,
        title: 'Pra Não Dizer Que Não Falei das Flores',
        track_duration: '00:05:26',
        album_id:19,
      },
      {
        track_number:11,
        title: 'Abrir Seus Olhos',
        track_duration: '00:01:57',
        album_id:19,
      },
      {
        track_number:12,
        title: '\'Green Goes\' (part. Sacramento MC\'s)',
        track_duration: '00:04:39',
        album_id:19,
      },
      {
        track_number:13,
        title: 'I Feel So Good Today',
        track_duration: '00:04:08',
        album_id:19,
      },
      {
        track_number:14,
        title: 'Peso da Batida do Errado que Deu Certo',
        track_duration: '00:02:06',
        album_id:19,
      },
      {
        track_number:15,
        title: 'Aquela Paz',
        track_duration: '00:02:56',
        album_id:19,
      },
      {
        track_number:16,
        title: 'Cada Cabeça Falante Tem Sua Tromba de Elefante (part. Rappin\' Hood)',
        track_duration: '00:04:28',
        album_id:19,
      },
      {
        track_number:17,
        title: 'Onde está o mundo bom? (Living in L.A.)',
        track_duration: '00:02:23',
        album_id:19,
      },
      {
        track_number:18,
        title: 'O Nosso Blues',
        track_duration: '00:05:27',
        album_id:19,
      },
      {
        track_number:19,
        title: 'O Futuro é um Labirinto pra Quem Não Sabe o que Quer',
        track_duration: '00:02:58',
        album_id:19,
      },
      {
        track_number:20,
        title: 'Na Palma da Mão (o Ragga da Baixada)',
        track_duration: '00:05:19',
        album_id:19,
      },
      {
        track_number:21,
        title: 'Skate Vibration',
        track_duration: '00:02:03',
        album_id:19,
      },
      {
        track_number:22,
        title: 'Criando Anticorpos',
        track_duration: '00:00:53',
        album_id:19,
      },
      {
        track_number:23,
        title: 'Dias de Luta, Dias de Glória',
        track_duration: '00:02:27',
        album_id:19,
      },
      {
        track_number:1,
        title: 'Pontes Indestrutíveis',
        track_duration: '00:03:32',
        album_id:20,
      },
      {
        track_number:2,
        title: 'O Que Ela Gosta é de Barriga',
        track_duration: '00:01:51',
        album_id:20,
      },
      {
        track_number:3,
        title: 'Não Viva em Vão',
        track_duration: '00:03:54',
        album_id:20,
      },
      {
        track_number:4,
        title: 'Ritmo, Ritual e Responsa',
        track_duration: '00:03:45',
        album_id:20,
      },
      {
        track_number:5,
        title: 'Be Myself',
        track_duration: '00:04:33',
        album_id:20,
      },
      {
        track_number:6,
        title: 'Uma Criança com Seu Olhar',
        track_duration: '00:04:13',
        album_id:20,
      },
      {
        track_number:7,
        title: 'Liberdade É Tudo (Instrumental)',
        track_duration: '00:01:43',
        album_id:20,
      },
      {
        track_number:8,
        title: 'O Universo a Nosso Favor (Participação Especial de Forfun)',
        track_duration: '00:04:22',
        album_id:20,
      },
      {
        track_number:9,
        title: 'Ninguém Entende Você',
        track_duration: '00:03:09',
        album_id:20,
      },
      {
        track_number:10,
        title: 'Quando Tudo Aconteceu (Instrumental)',
        track_duration: '00:02:15',
        album_id:20,
      },
      {
        track_number:11,
        title: 'Beco Sem Saída',
        track_duration: '00:03:57',
        album_id:20,
      },
      {
        track_number:12,
        title: 'Sem Medo da Escuridão (Participação Especial de MV Bill)',
        track_duration: '00:05:44',
        album_id:20,
      },
      {
        track_number:13,
        title: 'Nua, Linda e Inigualável',
        track_duration: '00:03:10',
        album_id:20,
      },
      {
        track_number:14,
        title: 'Vida de Magnata (Participação Especial de João Gord',
        track_duration: '00:02:44',
        album_id:20,
      },
      {
        track_number:15,
        title: 'Que Espécie de Vermes São Vocês? (Participação Especial de Marcon Lobotomi',
        track_duration: '00:02:03',
        album_id:20,
      },
      {
        track_number:16,
        title: 'Buscando um Novo Rumo (Instrumental)',
        track_duration: '00:02:41',
        album_id:20,
      },
      {
        track_number:17,
        title: 'Vivendo a Vida Numa Louca Viagem (Participação Especial de Sacramento MC\'s, programação e remix: DJ ',
        track_duration: '00:05:20',
        album_id:20,
      },
      {
        track_number:18,
        title: 'Curva de Hill',
        track_duration: '00:01:36',
        album_id:20,
      },
      {
        track_number:19,
        title: 'Direto e Reto Sempre',
        track_duration: '00:02:46',
        album_id:20,
      },
      {
        track_number:20,
        title: 'Skateboard Amor Eterno (Participação Especial de Sacramento MC\'s)',
        track_duration: '00:03:54',
        album_id:20,
      },
      {
        track_number:21,
        title: 'Café Foundation (Instrumental)',
        track_duration: '00:01:23',
        album_id:20,
      },
      {
        track_number:22,
        title: 'Paranormal (Participação Especial de Paranormal Attack)',
        track_duration: '00:08:12',
        album_id:20,
      },
      {
        track_number:23,
        title: 'Senhor do Tempo (Versão Ao Vivo (Expresso Brasil, ZL, São Paulo))',
        track_duration: '00:03:47',
        album_id:20,
      },
      {
        track_number:1,
        title: 'Dona do Meu Pensamento',
        track_duration: '00:03:59',
        album_id:21,
      },
      {
        track_number:2,
        title: 'Me Encontra',
        track_duration: '00:03:31',
        album_id:21,
      },
      {
        track_number:3,
        title: 'Só os Loucos Sabem',
        track_duration: '00:03:31',
        album_id:21,
      },
      {
        track_number:4,
        title: 'Inabalavelmente',
        track_duration: '00:04:25',
        album_id:21,
      },
      {
        track_number:5,
        title: 'Só Existe o Agora',
        track_duration: '00:04:28',
        album_id:21,
      },
      {
        track_number:6,
        title: 'Só pra Vadiar',
        track_duration: '00:04:05',
        album_id:21,
      },
      {
        track_number:7,
        title: 'Puro Sangue',
        track_duration: '00:04:08',
        album_id:21,
      },
      {
        track_number:8,
        title: 'O Dom, a Inteligência e a Voz',
        track_duration: '00:03:09',
        album_id:21,
      },
      {
        track_number:9,
        title: 'Os Cortes',
        track_duration: '00:04:23',
        album_id:21,
      },
      {
        track_number:10,
        title: 'Uma Só Vida pra Viver, Tenho Sede Nela Eu Vou',
        track_duration: '00:05:02',
        album_id:21,
      },
      {
        track_number:11,
        title: 'Viver Dias de Sol',
        track_duration: '00:04:19',
        album_id:21,
      },
      {
        track_number:12,
        title: 'Comigo Ninguém Tira Onda',
        track_duration: '00:02:59',
        album_id:21,
      },
      {
        track_number:13,
        title: 'Camisa 10 Joga Bola Até na Chuva (Bomba Sônica)',
        track_duration: '00:03:10',
        album_id:21,
      },
      {
        track_number:1,
        title: 'Um Dia a Gente se Encontra',
        track_duration: '00:03:04',
        album_id:22,
      },
      {
        track_number:2,
        title: 'Fina Arte',
        track_duration: '00:03:02',
        album_id:22,
      },
      {
        track_number:3,
        title: 'Cheia de Vida',
        track_duration: '00:02:42',
        album_id:22,
      },
      {
        track_number:4,
        title: 'Meu Novo Mundo',
        track_duration: '00:03:27',
        album_id:22,
      },
      {
        track_number:5,
        title: 'Do Jeito que eu Gosto, do Jeito que Eu Quero',
        track_duration: '00:04:27',
        album_id:22,
      },
      {
        track_number:6,
        title: 'Rock Star',
        track_duration: '00:03:18',
        album_id:22,
      },
      {
        track_number:7,
        title: 'Vem Ser Minha',
        track_duration: '00:04:38',
        album_id:22,
      },
      {
        track_number:8,
        title: 'Hoje Sou Eu que Não Mais te Quero',
        track_duration: '00:05:03',
        album_id:22,
      },
      {
        track_number:9,
        title: 'Camisa Preta',
        track_duration: '00:04:16',
        album_id:22,
      },
      {
        track_number:10,
        title: 'Vou me Embriagar de Você',
        track_duration: '00:04:25',
        album_id:22,
      },
      {
        track_number:11,
        title: 'A Mais Linda do Bar',
        track_duration: '00:03:34',
        album_id:22,
      },
      {
        track_number:12,
        title: 'Samba Triste',
        track_duration: '00:04:50',
        album_id:22,
      },
      {
        track_number:13,
        title: 'Contrastes da Vida',
        track_duration: '00:02:42',
        album_id:22,
      },
      {
        track_number:1,
        title: 'Quebra-Mar',
        track_duration: '00:01:56',
        album_id:23,
      },
      {
        track_number:2,
        title: 'O Que é da Casa é da Casa / Papo Reto',
        track_duration: '00:04:34',
        album_id:23,
      },
      {
        track_number:3,
        title: 'Zóio de Lula',
        track_duration: '00:03:47',
        album_id:23,
      },
      {
        track_number:4,
        title: 'Vícios e Virtudes',
        track_duration: '00:03:12',
        album_id:23,
      },
      {
        track_number:5,
        title: 'Hoje  (part.Marcelo Nova) (Cover do Camisa de Vênus)',
        track_duration: '00:04:25',
        album_id:23,
      },
      {
        track_number:6,
        title: 'O Preço',
        track_duration: '00:03:16',
        album_id:23,
      },
      {
        track_number:7,
        title: 'Tudo pro Alto',
        track_duration: '00:03:06',
        album_id:23,
      },
      {
        track_number:8,
        title: 'Não Uso Sapato',
        track_duration: '00:02:55',
        album_id:23,
      },
      {
        track_number:9,
        title: 'O Coro Vai Comê!',
        track_duration: '00:02:10',
        album_id:23,
      },
      {
        track_number:10,
        title: 'Tudo que Ela Gosta de Escutar',
        track_duration: '00:03:13',
        album_id:23,
      },
      {
        track_number:11,
        title: 'Não é Sério" (part. Negra ',
        track_duration: '00:05:18',
        album_id:23,
      },
      {
        track_number:12,
        title: 'Vinheta Beat Box II / Como Tudo Deve Ser',
        track_duration: '00:04:44',
        album_id:23,
      },
      {
        track_number:13,
        title: 'A Banca (Ratatá é Bicho Solto) (part. RZO)',
        track_duration: '00:04:02',
        album_id:23,
      },
      {
        track_number:14,
        title: 'Samba Makossa" (part. Marcelo D2) (Cover do Nação Zumi)',
        track_duration: '00:04:08',
        album_id:23,
      },
      {
        track_number:15,
        title: 'Quinta-Feira',
        track_duration: '00:05:19',
        album_id:23,
      },
      {
        track_number:16,
        title: 'Só Por Uma Noite',
        track_duration: '00:03:12',
        album_id:23,
      },
      {
        track_number:17,
        title: 'Oba, Lá Vem Ela" (Cover do Jorge Ben Jor)',
        track_duration: '00:02:49',
        album_id:23,
      },
      {
        track_number:18,
        title: 'Tudo Mudar',
        track_duration: '00:02:22',
        album_id:23,
      },
      {
        track_number:19,
        title: 'Proibida pra Mim (Grazon)',
        track_duration: '00:02:34',
        album_id:23,
      },
      {
        track_number:20,
        title: 'Charlie Brown Jr.',
        track_duration: '00:03:50',
        album_id:23,
      },
      {
        track_number:1,
        title: 'Resolve o Meu Problema Aí',
        track_duration: '00:00:45',
        album_id:24,
      },
      {
        track_number:2,
        title: 'O Coro Vai Comê!',
        track_duration: '00:01:55',
        album_id:24,
      },
      {
        track_number:3,
        title: 'Rubão, o Dono do Mundo',
        track_duration: '00:02:29',
        album_id:24,
      },
      {
        track_number:4,
        title: 'Tudo que Ela Gosta de Escutar',
        track_duration: '00:02:33',
        album_id:24,
      },
      {
        track_number:5,
        title: 'Me Encontra',
        track_duration: '00:03:18',
        album_id:24,
      },
      {
        track_number:6,
        title: 'Pontes Indestrutíveis',
        track_duration: '00:03:04',
        album_id:24,
      },
      {
        track_number:7,
        title: 'Te Levar',
        track_duration: '00:02:28',
        album_id:24,
      },
      {
        track_number:8,
        title: 'Dias de Luta, Dias de Glória',
        track_duration: '00:03:06',
        album_id:24,
      },
      {
        track_number:9,
        title: 'Descubra o Que Há De Errado Com Você',
        track_duration: '00:01:40',
        album_id:24,
      },
      {
        track_number:10,
        title: 'Coração Satânico (Participação Especial de Marcelo Nova)',
        track_duration: '00:04:31',
        album_id:24,
      },
      {
        track_number:11,
        title: 'Me Deixa (Participação Especial de Marcelo Falcão)',
        track_duration: '00:05:28',
        album_id:24,
      },
      {
        track_number:12,
        title: 'Não é Sério (Participação Especial de Marcelo Falcão)',
        track_duration: '00:05:17',
        album_id:24,
      },
      {
        track_number:13,
        title: 'Proibida pra Mim (Grazon)" (Participação Especial de Zeca Baleiro e Tuco Marcondes)',
        track_duration: '00:03:51',
        album_id:24,
      },
      {
        track_number:14,
        title: 'Longe de Você',
        track_duration: '00:03:35',
        album_id:24,
      },
      {
        track_number:15,
        title: 'Céu Azul (Versão de estúdio)',
        track_duration: '00:03:20',
        album_id:24,
      },
      {
        track_number:1,
        title: 'Céu Azul  ',
        track_duration: '00:03:17',
        album_id:25,
      },
      {
        track_number:2,
        title: 'Pipeline (cover The Chantays)  ',
        track_duration: '00:01:57',
        album_id:25,
      },
      {
        track_number:3,
        title: 'Papo Reto (Prazer é Sexo, o Resto é Negócio)  ',
        track_duration: '00:03:24',
        album_id:25,
      },
      {
        track_number:4,
        title: 'Só os Loucos Sabem  ',
        track_duration: '00:03:11',
        album_id:25,
      },
      {
        track_number:5,
        title: 'Ela Vai Voltar (Todos os Defeitos de uma Mulher Perfeita)  ',
        track_duration: '00:03:11',
        album_id:25,
      },
      {
        track_number:6,
        title: 'Hoje Eu Só Procuro a Minha Paz / Lutar pelo Que É Meu  ',
        track_duration: '00:04:43',
        album_id:25,
      },
      {
        track_number:7,
        title: 'No Passo a Passo  ',
        track_duration: '00:01:34',
        album_id:25,
      },
      {
        track_number:8,
        title: 'Tudo Pro Alto  ',
        track_duration: '00:03:06',
        album_id:25,
      },
      {
        track_number:9,
        title: 'Quinta Feira  ',
        track_duration: '00:02:04',
        album_id:25,
      },
      {
        track_number:10,
        title: 'Hoje Eu Acordei Feliz  ',
        track_duration: '00:02:29',
        album_id:25,
      },
      {
        track_number:11,
        title: 'Lugar ao Sol  ',
        track_duration: '00:03:16',
        album_id:25,
      },
      {
        track_number:12,
        title: 'Parta a Mil (Participação Especial de Márcio Mello)',
        track_duration: '00:01:24',
        album_id:25,
      },
      {
        track_number:13,
        title: 'Mantenha a Dúvida e Espere Até Ouvir Falar de Nós  ',
        track_duration: '00:03:03',
        album_id:25,
      },
      {
        track_number:14,
        title: 'Não Deixe o Mar Te Engolir  ',
        track_duration: '00:05:50',
        album_id:25,
      },
      {
        track_number:1,
        title: 'Yoga, Stress e Cafeína',
        track_duration: '00:04:14',
        album_id:26,
      },
      {
        track_number:2,
        title: 'Odisséia',
        track_duration: '00:03:49',
        album_id:26,
      },
      {
        track_number:3,
        title: 'Inutilia Truncat',
        track_duration: '00:00:51',
        album_id:26,
      },
      {
        track_number:4,
        title: 'Déjà Vu',
        track_duration: '00:02:14',
        album_id:26,
      },
      {
        track_number:5,
        title: 'Rubraglossina',
        track_duration: '00:03:07',
        album_id:26,
      },
      {
        track_number:6,
        title: 'Cicatrizes',
        track_duration: '00:02:43',
        album_id:26,
      },
      {
        track_number:7,
        title: 'Owiotúzio',
        track_duration: '00:03:01',
        album_id:26,
      },
      {
        track_number:8,
        title: 'Os 5 Segundos Que Precedem a Sua Queda',
        track_duration: '00:01:57',
        album_id:26,
      },
      {
        track_number:9,
        title: 'Álamo',
        track_duration: '00:03:33',
        album_id:26,
      },
      {
        track_number:10,
        title: 'Sobreviver',
        track_duration: '00:03:06',
        album_id:26,
      },
      {
        track_number:11,
        title: 'M. E. I.',
        track_duration: '00:07:26',
        album_id:26,
      },
      {
        track_number:1,
        title: 'Canto Gritando',
        track_duration: '00:03:46',
        album_id:27,
      },
      {
        track_number:2,
        title: 'Respeito É a Lei',
        track_duration: '00:03:53',
        album_id:27,
      },
      {
        track_number:3,
        title: 'Temporário',
        track_duration: '00:03:03',
        album_id:27,
      },
      {
        track_number:4,
        title: 'Liberta',
        track_duration: '00:02:43',
        album_id:27,
      },
      {
        track_number:5,
        title: 'Escadacronia',
        track_duration: '00:04:50',
        album_id:27,
      },
      {
        track_number:6,
        title: 'Bem Aqui',
        track_duration: '00:04:04',
        album_id:27,
      },
      {
        track_number:7,
        title: 'Voar',
        track_duration: '00:03:07',
        album_id:27,
      },
      {
        track_number:8,
        title: 'Quarto Escuro',
        track_duration: '00:03:05',
        album_id:27,
      },
      {
        track_number:9,
        title: 'Castelo',
        track_duration: '00:04:51',
        album_id:27,
      },
      {
        track_number:10,
        title: 'Cresci',
        track_duration: '00:07:18',
        album_id:27,
      },
      {
        track_number:1,
        title: 'Ritual',
        track_duration: '00:04:02',
        album_id:28,
      },
      {
        track_number:2,
        title: 'Planto',
        track_duration: '00:02:45',
        album_id:28,
      },
      {
        track_number:3,
        title: 'Jeito Livre',
        track_duration: '00:03:46',
        album_id:28,
      },
      {
        track_number:4,
        title: 'Mãe',
        track_duration: '00:03:12',
        album_id:28,
      },
      {
        track_number:5,
        title: '05: 20',
        track_duration: '00:04:54',
        album_id:28,
      },
      {
        track_number:6,
        title: 'Mulher',
        track_duration: '00:03:57',
        album_id:28,
      },
      {
        track_number:7,
        title: 'Escravo Espiritual',
        track_duration: '00:02:05',
        album_id:28,
      },
      {
        track_number:8,
        title: 'Samba',
        track_duration: '00:03:21',
        album_id:28,
      },
      {
        track_number:9,
        title: 'Transa',
        track_duration: '00:03:42',
        album_id:28,
      },
      {
        track_number:10,
        title: 'Seleção Natural',
        track_duration: '00:05:21',
        album_id:28,
      },
      {
        track_number:11,
        title: 'Inocentes',
        track_duration: '00:03:38',
        album_id:28,
      },
      {
        track_number:12,
        title: 'A Ponte',
        track_duration: '00:04:17',
        album_id:28,
      },
      {
        track_number:1,
        title: 'Escravo Espiritual (ao vivo) 2014',
        track_duration: '00:02:54',
        album_id:29,
      },
      {
        track_number:2,
        title: 'Samba (ao vivo) 2014',
        track_duration: '00:03:57',
        album_id:29,
      },
      {
        track_number:3,
        title: 'Jeito Livre (ao vivo) 2014',
        track_duration: '00:04:23',
        album_id:29,
      },
      {
        track_number:4,
        title: 'Ritual (ao vivo) 2014',
        track_duration: '00:05:19',
        album_id:29,
      },
      {
        track_number:5,
        title: 'Liberta + Respeito é a Lei (ao vivo) 2014',
        track_duration: '00:06:43',
        album_id:29,
      },
      {
        track_number:6,
        title: 'Planto (ao vivo) 2014',
        track_duration: '00:02:51',
        album_id:29,
      },
      {
        track_number:7,
        title: 'Escadacronia (ao vivo) 2014',
        track_duration: '00:05:24',
        album_id:29,
      },
      {
        track_number:8,
        title: 'Temporário (ao vivo) 2014',
        track_duration: '00:03:19',
        album_id:29,
      },
      {
        track_number:9,
        title: 'Inocentes (ao vivo) 2014',
        track_duration: '00:05:46',
        album_id:29,
      },
      {
        track_number:10,
        title: 'Infinito (ao vivo) 2014',
        track_duration: '00:03:20',
        album_id:29,
      },
      {
        track_number:11,
        title: 'M.E.I. (ao vivo) 2014',
        track_duration: '00:06:06',
        album_id:29,
      },
      {
        track_number:12,
        title: 'Seleção Natural (ao vivo) 2014',
        track_duration: '00:06:30',
        album_id:29,
      },
      {
        track_number:13,
        title: 'Quarto Escuro – part. Capilé (ao vivo) 2014',
        track_duration: '00:04:15',
        album_id:29,
      },
      {
        track_number:14,
        title: 'Cresci (ao vivo) 2014',
        track_duration: '00:08:54',
        album_id:29,
      },
      {
        track_number:15,
        title: 'Yoga, Stress e Cafeína (ao vivo) 2014',
        track_duration: '00:06:38',
        album_id:29,
      },
      {
        track_number:16,
        title: 'Aventura / O Vôo da Águia',
        track_duration: '00:03:20',
        album_id:29,
      },
      {
        track_number:17,
        title: 'Infinito',
        track_duration: '00:03:25',
        album_id:29,
      },
      {
        track_number:18,
        title: 'Bichos Escrotos (Titãs)',
        track_duration: '00:02:54',
        album_id:29,
      },
      {
        track_number:19,
        title: 'Samba (ao vivo) 2012',
        track_duration: '00:03:30',
        album_id:29,
      },
      {
        track_number:20,
        title: 'Transa + 5:20 + Mãe (ao vivo) 2012',
        track_duration: '00:13:10',
        album_id:29,
      },
      {
        track_number:21,
        title: 'Mulher (ao vivo) 2012',
        track_duration: '00:04:06',
        album_id:29,
      },
      {
        track_number:22,
        title: 'Ritual + Respeito é a Lei + Liberta (ao vivo) 2012',
        track_duration: '00:11:02',
        album_id:29,
      },
      {
        track_number:23,
        title: 'Quarto Escuro (ao vivo) 2012',
        track_duration: '00:03:28',
        album_id:29,
      },
      {
        track_number:24,
        title: 'Seleção Natural (ao vivo) 2012',
        track_duration: '00:05:28',
        album_id:29,
      },
      {
        track_number:25,
        title: 'Inocentes (ao vivo) 2012',
        track_duration: '00:04:58',
        album_id:29,
      },
      {
        track_number:26,
        title: 'O Menino e o Diabo do Rio (2006)',
        track_duration: '00:05:02',
        album_id:29,
      },
      {
        track_number:27,
        title: 'Voltaremos (2004)',
        track_duration: '00:01:38',
        album_id:29,
      },
      {
        track_number:28,
        title: 'O que já foi (2003)',
        track_duration: '00:01:44',
        album_id:29,
      },
      {
        track_number:29,
        title: 'Valentino Caixa-Alta (2003)',
        track_duration: '00:04:11',
        album_id:29,
      },
      {
        track_number:30,
        title: 'Cão Simas (2002)',
        track_duration: '00:02:01',
        album_id:29,
      },
      {
        track_number:31,
        title: 'Horas?! (2002)',
        track_duration: '00:02:24',
        album_id:29,
      },
      {
        track_number:1,
        title: 'Puteiro em João Pessoa',
        track_duration: '00:03:07',
        album_id:30,
      },
      {
        track_number:2,
        title: 'Palhas do Coqueiro',
        track_duration: '00:01:58',
        album_id:30,
      },
      {
        track_number:3,
        title: 'MM\'s',
        track_duration: '00:01:59',
        album_id:30,
      },
      {
        track_number:4,
        title: 'Minha Cunhada',
        track_duration: '00:01:21',
        album_id:30,
      },
      {
        track_number:5,
        title: 'Rapante',
        track_duration: '00:03:03',
        album_id:30,
      },
      {
        track_number:6,
        title: 'Carro Forte',
        track_duration: '00:01:29',
        album_id:30,
      },
      {
        track_number:7,
        title: 'Nêga Jurema',
        track_duration: '00:01:52',
        album_id:30,
      },
      {
        track_number:8,
        title: 'Deixei de Fumar / "Cana Caiana',
        track_duration: '00:01:30',
        album_id:30,
      },
      {
        track_number:9,
        title: 'Cajueiro / "Rio das Pedras',
        track_duration: '00:02:30',
        album_id:30,
      },
      {
        track_number:10,
        title: 'Bê a Bá',
        track_duration: '00:02:30',
        album_id:30,
      },
      {
        track_number:11,
        title: 'Bicharada',
        track_duration: '00:01:37',
        album_id:30,
      },
      {
        track_number:12,
        title: 'Marujo',
        track_duration: '00:02:31',
        album_id:30,
      },
      {
        track_number:13,
        title: 'Cintura Fina',
        track_duration: '00:02:35',
        album_id:30,
      },
      {
        track_number:14,
        title: 'Selim',
        track_duration: '00:04:12',
        album_id:30,
      },
      {
        track_number:15,
        title: 'Puteiro em João Pessoa II" (faixa bônus da edição em CD)',
        track_duration: '00:03:07',
        album_id:30,
      },
      {
        track_number:16,
        title: 'Selim (acústico, faixa bônus da edição em CD)',
        track_duration: '00:04:12',
        album_id:30,
      },
      {
        track_number:1,
        title: 'Tora Tora (Canisso / Rodolfo / Digão)',
        track_duration: '00:04:15',
        album_id:31,
      },
      {
        track_number:2,
        title: 'Eu Quero Ver o Oco (Canisso / Rodolfo / Digão)',
        track_duration: '00:04:12',
        album_id:31,
      },
      {
        track_number:3,
        title: 'Opa! Peraí, Caceta (Canisso / Rodolfo / Digão)',
        track_duration: '00:02:29',
        album_id:31,
      },
      {
        track_number:4,
        title: 'O Pão da Minha Prima (Tio Jovem / Zenilton)',
        track_duration: '00:02:41',
        album_id:31,
      },
      {
        track_number:5,
        title: 'Pitando no Kombão (Canisso / Digão / Rodolfo)',
        track_duration: '00:01:44',
        album_id:31,
      },
      {
        track_number:6,
        title: 'Bestinha (Digão / Rodolfo)',
        track_duration: '00:02:29',
        album_id:31,
      },
      {
        track_number:7,
        title: 'Esporrei na Manivela (Domínio público / Digão / Guilherme Bonolo / Paulinho Mattos / Rodolfo / Fred)',
        track_duration: '00:04:07',
        album_id:31,
      },
      {
        track_number:8,
        title: 'Tá Querendo Desquitar (Ela Tá Dando) (Guriata do Coqueiro / Zeniton)',
        track_duration: '00:03:06',
        album_id:31,
      },
      {
        track_number:9,
        title: 'Sereia da Pedreira (Rodolfo)',
        track_duration: '00:01:48',
        album_id:31,
      },
      {
        track_number:10,
        title: 'I Saw You Saying (That You Say That You Saw) (Rodolfo / Gabriel Thomáz)',
        track_duration: '00:03:25',
        album_id:31,
      },
      {
        track_number:11,
        title: 'Cabeça de Bode (Digão / Rodolfo)',
        track_duration: '00:01:59',
        album_id:31,
      },
      {
        track_number:12,
        title: 'Herbocinética (Rodolfo)',
        track_duration: '00:03:16',
        album_id:31,
      },
      {
        track_number:1,
        title: 'Infeliz Natal',
        track_duration: '00:02:17',
        album_id:32,
      },
      {
        track_number:2,
        title: 'A Sua',
        track_duration: '00:02:21',
        album_id:32,
      },
      {
        track_number:3,
        title: 'Papeau Nuky Doe',
        track_duration: '00:02:01',
        album_id:32,
      },
      {
        track_number:4,
        title: 'Merry Christmas',
        track_duration: '00:02:59',
        album_id:32,
      },
      {
        track_number:5,
        title: 'Bodies',
        track_duration: '00:02:59',
        album_id:32,
      },
      {
        track_number:6,
        title: 'Puteiro em João Pessoa (Remix)',
        track_duration: '00:03:15',
        album_id:32,
      },
      {
        track_number:7,
        title: 'Esporrei na Manivela (Ao Vivo no festival Hollywood Rock de 1996',
        track_duration: '00:04:52',
        album_id:32,
      },
      {
        track_number:8,
        title: 'Bê a Bá (Ao Vivo no festival Hollywood Rock de 1996',
        track_duration: '00:04:08',
        album_id:32,
      },
      {
        track_number:9,
        title: 'Cajueiro (Ao Vivo no festival Hollywood Rock de 1996',
        track_duration: '00:02:38',
        album_id:32,
      },
      {
        track_number:10,
        title: 'Palhas do Coqueiro (Ao Vivo no festival Hollywood Rock',
        track_duration: '00:02:13',
        album_id:32,
      },
      {
        track_number:1,
        title: 'Andar na Pedra',
        track_duration: '00:03:40',
        album_id:33,
      },
      {
        track_number:2,
        title: 'Véio, Manco e Gordo',
        track_duration: '00:01:03',
        album_id:33,
      },
      {
        track_number:3,
        title: 'O Toco',
        track_duration: '00:02:00',
        album_id:33,
      },
      {
        track_number:4,
        title: 'Poquito Más (Healthy Food)',
        track_duration: '00:02:45',
        album_id:33,
      },
      {
        track_number:5,
        title: 'Wipe Out',
        track_duration: '00:02:23',
        album_id:33,
      },
      {
        track_number:6,
        title: 'CC de Com Força',
        track_duration: '00:01:36',
        album_id:33,
      },
      {
        track_number:7,
        title: 'Crumis Ódamis',
        track_duration: '00:01:58',
        album_id:33,
      },
      {
        track_number:8,
        title: 'Bonita',
        track_duration: '00:02:03',
        album_id:33,
      },
      {
        track_number:9,
        title: 'Ui, Ui, Ui',
        track_duration: '00:00:47',
        album_id:33,
      },
      {
        track_number:10,
        title: 'Oliver’s Army (Cover de Elvis Costello)',
        track_duration: '00:02:12',
        album_id:33,
      },
      {
        track_number:11,
        title: 'Nariz de Doze',
        track_duration: '00:03:01',
        album_id:33,
      },
      {
        track_number:12,
        title: 'Pequena Raimunda (Ramona) (Cover de Ramones)',
        track_duration: '00:02:26',
        album_id:33,
      },
      {
        track_number:13,
        title: 'Baile Funky',
        track_duration: '00:04:00',
        album_id:33,
      },
      {
        track_number:14,
        title: 'Bass Hell (Bônus Crap)',
        track_duration: '00:03:25',
        album_id:33,
      },
      {
        track_number:1,
        title: 'Só no Forevis (Selim)',
        track_duration: '00:00:33',
        album_id:34,
      },
      {
        track_number:2,
        title: 'Mato Véio',
        track_duration: '00:02:07',
        album_id:34,
      },
      {
        track_number:3,
        title: 'Carrão de Dois',
        track_duration: '00:02:01',
        album_id:34,
      },
      {
        track_number:4,
        title: 'Fome do Cão',
        track_duration: '00:03:28',
        album_id:34,
      },
      {
        track_number:5,
        title: 'Mulher de Fases',
        track_duration: '00:03:32',
        album_id:34,
      },
      {
        track_number:6,
        title: 'Alegria',
        track_duration: '00:01:49',
        album_id:34,
      },
      {
        track_number:7,
        title: 'A Mais Pedida',
        track_duration: '00:03:52',
        album_id:34,
      },
      {
        track_number:8,
        title: 'Boca de Lata',
        track_duration: '00:02:26',
        album_id:34,
      },
      {
        track_number:9,
        title: 'Me Lambe',
        track_duration: '00:03:16',
        album_id:34,
      },
      {
        track_number:10,
        title: 'Pompem',
        track_duration: '00:02:42',
        album_id:34,
      },
      {
        track_number:11,
        title: 'Deixa Eu Falar',
        track_duration: '00:04:41',
        album_id:34,
      },
      {
        track_number:12,
        title: 'Aquela',
        track_duration: '00:03:24',
        album_id:34,
      },
      {
        track_number:13,
        title: 'Língua Presa',
        track_duration: '00:01:39',
        album_id:34,
      },
      {
        track_number:14,
        title: 'Mulher de Fases (A Linda)',
        track_duration: '00:06:22',
        album_id:34,
      },
      {
        track_number:1,
        title: 'Sanidade (Letra e música: Digão e Rodolfo. Vocal: Digão. Originalmente criada em 1992)',
        track_duration: '00:03:13',
        album_id:35,
      },
      {
        track_number:2,
        title: 'Desculpe, Mas Eu Vou Chorar (Letra e música: César Augusto e João Gabriel. Registrada em 1993 no pro',
        track_duration: '00:02:43',
        album_id:35,
      },
      {
        track_number:3,
        title: 'Nana Neném (Registrada em single de 1998)',
        track_duration: '00:01:31',
        album_id:35,
      },
      {
        track_number:4,
        title: 'Sheena Is A Punk Rocker (Ramones cover)',
        track_duration: '00:02:06',
        album_id:35,
      },
      {
        track_number:5,
        title: 'Rockaway Beach (Ramones cover)',
        track_duration: '00:01:44',
        album_id:35,
      },
      {
        track_number:6,
        title: 'Teenage Lobotomy (Ramones cover)',
        track_duration: '00:01:33',
        album_id:35,
      },
      {
        track_number:7,
        title: 'I Wanna Be Well (Ramones cover)',
        track_duration: '00:02:43',
        album_id:35,
      },
      {
        track_number:8,
        title: 'I Don\'t Care (Ramones cover)',
        track_duration: '00:01:30',
        album_id:35,
      },
      {
        track_number:9,
        title: 'Rock \'n\' Roll High School (Ramones cover)',
        track_duration: '00:01:47',
        album_id:35,
      },
      {
        track_number:10,
        title: 'Needles And Pins (cover da dupla Jack Nitzsche e Sonny Bono, com arranjo inspirado nos Ramones)',
        track_duration: '00:02:03',
        album_id:35,
      },
      {
        track_number:11,
        title: 'Do You Wanna Dance? (cover de Bobby Freeman, com arranjo inspirado nos Ramones)',
        track_duration: '00:01:24',
        album_id:35,
      },
      {
        track_number:12,
        title: 'Pinhead (Ramones cover)',
        track_duration: '00:01:56',
        album_id:35,
      },
      {
        track_number:13,
        title: 'Blitzkrieg Bop (Ramones cover)',
        track_duration: '00:02:23',
        album_id:35,
      },
      {
        track_number:1,
        title: 'Fique! Fique! (Letra: Telo, Digão. Música: Marquinho, Canisso, Digão)',
        track_duration: '00:02:52',
        album_id:36,
      },
      {
        track_number:2,
        title: 'Crocodilo Meio Kilo (Letra e música: Digão)',
        track_duration: '00:02:25',
        album_id:36,
      },
      {
        track_number:3,
        title: 'Joey (Letra: Digão, Telo. Música: Digão)',
        track_duration: '00:03:39',
        album_id:36,
      },
      {
        track_number:4,
        title: 'Vento Certo (Água da Mina) (Letra: Digão, Telo. Música: Digão)',
        track_duration: '00:02:33',
        album_id:36,
      },
      {
        track_number:5,
        title: 'Kavookavala (Letra: Telo. Música: Digão) (com Derrick Green)',
        track_duration: '00:03:42',
        album_id:36,
      },
      {
        track_number:6,
        title: 'El Mariachi (Letra: Digão, Telo. Música: Digão)',
        track_duration: '00:01:51',
        album_id:36,
      },
      {
        track_number:7,
        title: 'Mas Vó (Letra: Telo. Música: Digão)',
        track_duration: '00:04:18',
        album_id:36,
      },
      {
        track_number:8,
        title: 'Princesinha (Letra e música: Telo)',
        track_duration: '00:02:38',
        album_id:36,
      },
      {
        track_number:9,
        title: 'Uabarrêba (Letra: Digão, Telo. Música: Digão)',
        track_duration: '00:02:32',
        album_id:36,
      },
      {
        track_number:10,
        title: 'Atitude Severa (Letra: Telo, Digão, Gabriel. Música: Marquinho, Canisso)',
        track_duration: '00:02:47',
        album_id:36,
      },
      {
        track_number:11,
        title: 'Pegamutukalá (Letra: Mr. Catra, DJ Leandro Neurose, Telo, Digão. Música: Marquinho, Digão) (com Mr. ',
        track_duration: '00:03:48',
        album_id:36,
      },
      {
        track_number:12,
        title: 'Baixo Calão (Letra: Telo, Digão. Música: Canisso, Marquinho, Digão)',
        track_duration: '00:02:53',
        album_id:36,
      },
      {
        track_number:1,
        title: 'Cachorrinha (part. Frango do Galinha Preta)',
        track_duration: '00:02:05',
        album_id:37,
      },
      {
        track_number:2,
        title: 'BOP',
        track_duration: '00:03:15',
        album_id:37,
      },
      {
        track_number:3,
        title: 'Baculejo',
        track_duration: '00:03:11',
        album_id:37,
      },
      {
        track_number:4,
        title: 'Gato da Rosinha',
        track_duration: '00:02:00',
        album_id:37,
      },
      {
        track_number:5,
        title: 'Cera Quente',
        track_duration: '00:03:52',
        album_id:37,
      },
      {
        track_number:6,
        title: 'Rafael',
        track_duration: '00:02:03',
        album_id:37,
      },
      {
        track_number:7,
        title: 'Descendo na Banguela',
        track_duration: '00:03:01',
        album_id:37,
      },
      {
        track_number:8,
        title: 'Dubmundos (part. Sen Dog do Cypress Hill)',
        track_duration: '00:04:06',
        album_id:37,
      },
      {
        track_number:9,
        title: 'Nó Suíno',
        track_duration: '00:02:14',
        album_id:37,
      },
      {
        track_number:10,
        title: 'Importada do Interior',
        track_duration: '00:02:53',
        album_id:37,
      },
      {
        track_number:11,
        title: 'Gordelícia',
        track_duration: '00:03:21',
        album_id:37,
      },
      {
        track_number:12,
        title: 'Politics (part. Cipriano e Billy Graziadei)',
        track_duration: '00:05:14',
        album_id:37,
      },
      {
        track_number:1,
        title: 'Pemba Talk',
        track_duration: '00:02:58',
        album_id:38,
      },
      {
        track_number:2,
        title: 'Sol e Lua',
        track_duration: '00:02:31',
        album_id:38,
      },
      {
        track_number:3,
        title: 'Oversize',
        track_duration: '00:02:00',
        album_id:38,
      },
      {
        track_number:4,
        title: 'Folha de Zinco',
        track_duration: '00:02:50',
        album_id:38,
      },
      {
        track_number:5,
        title: 'Macaxeira',
        track_duration: '00:01:39',
        album_id:38,
      },
      {
        track_number:1,
        title: 'Fome do cão (Ao vivo)',
        track_duration: '00:04:00',
        album_id:39,
      },
      {
        track_number:2,
        title: 'Mato véio (Ao vivo)',
        track_duration: '00:02:08',
        album_id:39,
      },
      {
        track_number:3,
        title: 'Carrão de dois (Ao vivo)',
        track_duration: '00:02:00',
        album_id:39,
      },
      {
        track_number:4,
        title: 'Nêga Jurema (Ao vivo)',
        track_duration: '00:01:46',
        album_id:39,
      },
      {
        track_number:5,
        title: 'Be a bá (Ao vivo)',
        track_duration: '00:03:14',
        album_id:39,
      },
      {
        track_number:6,
        title: 'Pompem (Ao vivo)',
        track_duration: '00:02:36',
        album_id:39,
      },
      {
        track_number:7,
        title: 'O pão da minha prima (Ao vivo)',
        track_duration: '00:02:34',
        album_id:39,
      },
      {
        track_number:8,
        title: 'Pequena raimunda (Ao vivo)',
        track_duration: '00:01:31',
        album_id:39,
      },
      {
        track_number:9,
        title: 'Bonita (Ao vivo)',
        track_duration: '00:02:01',
        album_id:39,
      },
      {
        track_number:10,
        title: 'Língua presa (Ao vivo)',
        track_duration: '00:01:34',
        album_id:39,
      },
      {
        track_number:11,
        title: 'Opa! Peraí, caceta (Ao vivo)',
        track_duration: '00:02:36',
        album_id:39,
      },
      {
        track_number:12,
        title: 'Sereia da pedreira (Ao vivo)',
        track_duration: '00:01:56',
        album_id:39,
      },
      {
        track_number:13,
        title: 'I Saw You Saying (That You Say That You Saw)',
        track_duration: '00:03:34',
        album_id:39,
      },
      {
        track_number:14,
        title: 'Andar na pedra (Ao vivo)',
        track_duration: '00:03:36',
        album_id:39,
      },
      {
        track_number:15,
        title: 'Eu quero ver o oco (Ao vivo)',
        track_duration: '00:04:21',
        album_id:39,
      },
      {
        track_number:16,
        title: 'Selim (Ao vivo)',
        track_duration: '00:02:48',
        album_id:39,
      },
      {
        track_number:17,
        title: 'Marujo (Ao vivo)',
        track_duration: '00:02:33',
        album_id:39,
      },
      {
        track_number:18,
        title: 'Deixei de fumar (Cachimbo da mulher) [Ao vivo]',
        track_duration: '00:01:30',
        album_id:39,
      },
      {
        track_number:19,
        title: 'Tá querendo desquitar (Ao vivo)',
        track_duration: '00:07:13',
        album_id:39,
      },
      {
        track_number:20,
        title: 'Boca de lata (Ao vivo)',
        track_duration: '00:03:07',
        album_id:39,
      },
      {
        track_number:21,
        title: 'Herbocinética (Ao vivo)',
        track_duration: '00:03:02',
        album_id:39,
      },
      {
        track_number:22,
        title: 'Poquito más (Healthy Food) [Ao vivo]',
        track_duration: '00:02:50',
        album_id:39,
      },
      {
        track_number:23,
        title: 'Rapante (Ao vivo)',
        track_duration: '00:03:18',
        album_id:39,
      },
      {
        track_number:24,
        title: 'Puteiro em João Pessoa (Ao vivo)',
        track_duration: '00:04:01',
        album_id:39,
      },
      {
        track_number:25,
        title: 'A mais pedida (Ao vivo)',
        track_duration: '00:03:45',
        album_id:39,
      },
      {
        track_number:26,
        title: 'Deixa eu falar (Ao vivo)',
        track_duration: '00:04:44',
        album_id:39,
      },
      {
        track_number:27,
        title: 'Pitando no kombão (Ao vivo)',
        track_duration: '00:01:43',
        album_id:39,
      },
      {
        track_number:28,
        title: 'Palhas do coqueiro (Ao vivo)',
        track_duration: '00:02:06',
        album_id:39,
      },
      {
        track_number:29,
        title: 'Papeau Nuky Doe (Ao vivo)',
        track_duration: '00:02:09',
        album_id:39,
      },
      {
        track_number:30,
        title: 'Oliver\'s Army (Ao vivo)',
        track_duration: '00:02:13',
        album_id:39,
      },
      {
        track_number:31,
        title: 'Minha cunhada / You\'re Gonna Kill That Girl (Ao vivo)',
        track_duration: '00:01:40',
        album_id:39,
      },
      {
        track_number:32,
        title: 'Baile funky (Ao vivo)',
        track_duration: '00:04:01',
        album_id:39,
      },
      {
        track_number:33,
        title: 'Tora tora (Ao vivo)',
        track_duration: '00:04:37',
        album_id:39,
      },
      {
        track_number:34,
        title: 'Esporrei na manivela (Ao vivo)',
        track_duration: '00:04:08',
        album_id:39,
      },
      {
        track_number:35,
        title: 'Nariz de doze (Ao vivo)',
        track_duration: '00:02:52',
        album_id:39,
      },
      {
        track_number:36,
        title: 'Me lambe (Ao vivo)',
        track_duration: '00:04:12',
        album_id:39,
      },
      {
        track_number:37,
        title: 'Bestinha (Ao vivo)',
        track_duration: '00:02:06',
        album_id:39,
      },
      {
        track_number:38,
        title: 'Mulher de fases (Ao vivo)',
        track_duration: '00:04:01',
        album_id:39,
      },
      {
        track_number:39,
        title: 'Reggae do manero (Ao vivo)',
        track_duration: '00:06:00',
        album_id:39,
      },
      {
        track_number:40,
        title: '20 e poucos anos (Ao vivo)',
        track_duration: '00:02:04',
        album_id:39,
      },
      {
        track_number:1,
        title: 'Intro Roda Viva',
        track_duration: '00:01:39',
        album_id:40,
      },
      {
        track_number:2,
        title: 'Fique Fique',
        track_duration: '00:02:51',
        album_id:40,
      },
      {
        track_number:3,
        title: 'Esporrei Na Manivela',
        track_duration: '00:05:13',
        album_id:40,
      },
      {
        track_number:4,
        title: 'Jaws',
        track_duration: '00:03:57',
        album_id:40,
      },
      {
        track_number:5,
        title: 'Marujo',
        track_duration: '00:02:54',
        album_id:40,
      },
      {
        track_number:6,
        title: 'Rapante',
        track_duration: '00:03:26',
        album_id:40,
      },
      {
        track_number:7,
        title: 'Opa Peraí Caceta',
        track_duration: '00:02:15',
        album_id:40,
      },
      {
        track_number:8,
        title: 'Pompem',
        track_duration: '00:02:44',
        album_id:40,
      },
      {
        track_number:9,
        title: 'Pão Da Minha Prima',
        track_duration: '00:02:56',
        album_id:40,
      },
      {
        track_number:10,
        title: 'Mulher De Fases',
        track_duration: '00:04:32',
        album_id:40,
      },
      {
        track_number:11,
        title: 'Palhas Do Coqueiro',
        track_duration: '00:02:42',
        album_id:40,
      },
      {
        track_number:12,
        title: 'Bê A Bá',
        track_duration: '00:03:22',
        album_id:40,
      },
      {
        track_number:13,
        title: 'Macaxera',
        track_duration: '00:01:47',
        album_id:40,
      },
      {
        track_number:14,
        title: 'Pitando No Kombão',
        track_duration: '00:01:40',
        album_id:40,
      },
      {
        track_number:1,
        title: 'Cachorrinha (part. Frango do Galinha Preta)',
        track_duration: '00:02:07',
        album_id:41,
      },
      {
        track_number:2,
        title: 'BOP',
        track_duration: '00:03:08',
        album_id:41,
      },
      {
        track_number:3,
        title: 'Baculejo',
        track_duration: '00:03:12',
        album_id:41,
      },
      {
        track_number:4,
        title: 'O Gato da Rosinha',
        track_duration: '00:02:00',
        album_id:41,
      },
      {
        track_number:5,
        title: 'Cera Quente',
        track_duration: '00:03:41',
        album_id:41,
      },
      {
        track_number:6,
        title: 'Rafael',
        track_duration: '00:02:08',
        album_id:41,
      },
      {
        track_number:7,
        title: 'Descendo na Banguela',
        track_duration: '00:03:06',
        album_id:41,
      },
      {
        track_number:8,
        title: 'Dubmundos (part. Sen Dog do Cypress Hill)',
        track_duration: '00:04:14',
        album_id:41,
      },
      {
        track_number:9,
        title: 'Nó Suíno',
        track_duration: '00:02:35',
        album_id:41,
      },
      {
        track_number:10,
        title: 'Importada do Interior',
        track_duration: '00:02:56',
        album_id:41,
      },
      {
        track_number:11,
        title: 'Gordelícia',
        track_duration: '00:03:46',
        album_id:41,
      },
      {
        track_number:12,
        title: 'Politics (part. Cipriano)',
        track_duration: '00:05:12',
        album_id:41,
      },
      {
        track_number:13,
        title: 'Mas Vó',
        track_duration: '00:04:29',
        album_id:41,
      },
      {
        track_number:14,
        title: 'Eu Quero Ver o Oco',
        track_duration: '00:03:51',
        album_id:41,
      },
      {
        track_number:15,
        title: 'Esporrei na Manivela',
        track_duration: '00:04:44',
        album_id:41,
      },
      {
        track_number:16,
        title: 'Be a Bá',
        track_duration: '00:03:22',
        album_id:41,
      },
      {
        track_number:17,
        title: 'Puteiro em João Pessoa',
        track_duration: '00:03:09',
        album_id:41,
      },
      {
        track_number:1,
        title: 'Gordelícia (Ao Vivo | Acústico)',
        track_duration: '00:03:39',
        album_id:42,
      },
      {
        track_number:2,
        title: 'Palhas do Coqueiro (Ao Vivo | Acústico)',
        track_duration: '00:02:58',
        album_id:42,
      },
      {
        track_number:3,
        title: 'O Pão da Minha Prima / Monkey Man (Ao Vivo | Acústico)',
        track_duration: '00:03:12',
        album_id:42,
      },
      {
        track_number:4,
        title: 'Papeau Nuck Doe (Ao Vivo | Acústico)',
        track_duration: '00:02:10',
        album_id:42,
      },
      {
        track_number:5,
        title: 'Rapante (Ao Vivo | Acústico)',
        track_duration: '00:04:02',
        album_id:42,
      },
      {
        track_number:6,
        title: 'Sereia da Pedreira (Ao Vivo | Acústico)',
        track_duration: '00:02:17',
        album_id:42,
      },
      {
        track_number:7,
        title: 'El Mariachi (Ao Vivo | Acústico)',
        track_duration: '00:02:41',
        album_id:42,
      },
      {
        track_number:8,
        title: 'Nega Jurema (Ao Vivo | Acústico)',
        track_duration: '00:02:11',
        album_id:42,
      },
      {
        track_number:9,
        title: 'I Saw You Saying (That You Say That You Saw) (Ao Vivo | Acústico)',
        track_duration: '00:04:50',
        album_id:42,
      },
      {
        track_number:10,
        title: 'Bê a Bá (Ao Vivo | Acústico)',
        track_duration: '00:04:01',
        album_id:42,
      },
      {
        track_number:11,
        title: 'Mulher de Fases (Ao Vivo | Acústico)',
        track_duration: '00:04:51',
        album_id:42,
      },
      {
        track_number:12,
        title: 'Mas Vó... (Ao Vivo | Acústico)',
        track_duration: '00:04:38',
        album_id:42,
      },
      {
        track_number:13,
        title: 'Dubmundos (Ao Vivo | Acústico)',
        track_duration: '00:05:12',
        album_id:42,
      },
      {
        track_number:14,
        title: 'Bonita (Ao Vivo | Acústico)',
        track_duration: '00:02:48',
        album_id:42,
      },
      {
        track_number:15,
        title: 'Opa! Peraí, Caceta (Ao Vivo | Acústico)',
        track_duration: '00:02:30',
        album_id:42,
      },
      {
        track_number:16,
        title: 'Baculejo (Ao Vivo | Acústico)',
        track_duration: '00:03:42',
        album_id:42,
      },
      {
        track_number:17,
        title: 'A Mais Pedida (Ao Vivo | Acústico)',
        track_duration: '00:03:43',
        album_id:42,
      },
      {
        track_number:18,
        title: 'Reggae do Manero (Ao Vivo | Acústico)',
        track_duration: '00:05:25',
        album_id:42,
      },
      {
        track_number:19,
        title: 'Selim (Ao Vivo | Acústico)',
        track_duration: '00:04:50',
        album_id:42,
      },
      {
        track_number:20,
        title: 'Cintura Fina (Ao Vivo | Acústico)',
        track_duration: '00:03:00',
        album_id:42,
      },
      {
        track_number:21,
        title: 'Cera Quente (Ao Vivo | Acústico)',
        track_duration: '00:03:58',
        album_id:42,
      },
      {
        track_number:22,
        title: 'Deixa Eu Falar (Ao Vivo | Acústico)',
        track_duration: '00:04:38',
        album_id:42,
      },
      {
        track_number:23,
        title: 'Lugar Ao Sol (Ao Vivo | Acústico)',
        track_duration: '00:03:40',
        album_id:42,
      },
      {
        track_number:24,
        title: 'Me Lambe (Ao Vivo | Acústico)',
        track_duration: '00:04:30',
        album_id:42,
      },
      {
        track_number:25,
        title: 'Puteiro Em João Pessoa (Ao Vivo | Acústico)',
        track_duration: '00:03:25',
        album_id:42,
      },
      {
        track_number:26,
        title: 'Esporrei Na Manivela (Ao Vivo | Acústico)',
        track_duration: '00:05:13',
        album_id:42,
      },
      {
        track_number:27,
        title: 'Eu Quero Ver o Oco (Ao Vivo | Acústico)',
        track_duration: '00:04:22',
        album_id:42,
      }


    ])
  }
}

module.exports = TrackSeeder
